PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Email" TEXT NOT NULL,
    "CreatedAt" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Price" REAL NOT NULL,
    "Stock" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UserId" INTEGER NOT NULL,
    "Total" REAL NOT NULL,
    "PlacedAt" TEXT NOT NULL,
    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE IF NOT EXISTS "OrderItems" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "OrderId" INTEGER NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "Quantity" INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id"),
    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id")
);

