PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Email" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Addresses" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UserId" INTEGER NOT NULL,
    "Line1" TEXT NOT NULL,
    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UserId" INTEGER NOT NULL,
    "AddressId" INTEGER NOT NULL,
    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id"),
    FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id")
);

