PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "events" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TEXT NULL
);

