import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, Scale, Code2, Server, AlertCircle, FileCheck } from 'lucide-react';
import Footer from '../../components/layout/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service — Namines',
  description: 'Terms and conditions governing the use of Namines database lifecycle engine and compiler platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface-900 text-content-primary flex flex-col justify-between">
      <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-20">
        {/* Back link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-xs font-mono text-content-muted hover:text-content-primary mb-8 transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Namines</span>
        </Link>

        {/* Header */}
        <div className="border-b border-surface-500/80 pb-8 mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface-800 border border-surface-500 text-micro font-mono text-accent-text mb-4">
            <Scale className="w-3.5 h-3.5" />
            <span>Developer-First Agreement</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-content-primary mb-3">
            Terms of Service
          </h1>
          <p className="text-xs font-mono text-content-subtle">
            Effective Date: September 7, 2026 &bull; Version 2.2
          </p>
        </div>

        {/* Content Body */}
        <div className="space-y-12 text-sm text-content-secondary leading-relaxed">
          {/* Section 1: Agreement */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-content-primary tracking-tight">
              1. Acceptance &amp; Service Scope
            </h2>
            <p>
              By accessing or using Namines (including our web platform, API, CLI tooling, and Model Context Protocol servers), you agree to be bound by these Terms of Service. If you are entering into this agreement on behalf of a company, organization, or legal entity, you represent that you possess the authority to bind such entity.
            </p>
            <p>
              Namines provides automated database architecture design, deterministic SQL DDL compilation, schema migration risk classification, and ephemeral test validation for development teams.
            </p>
          </section>

          {/* Section 2: 100% Customer Ownership */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-content-primary tracking-tight flex items-center gap-2">
              <Code2 className="w-5 h-5 text-accent-text" />
              <span>2. 100% Customer Ownership &amp; Zero Lock-In</span>
            </h2>
            <div className="rounded-[var(--radius-card)] border border-accent/30 bg-surface-800/60 p-5 space-y-3">
              <p className="text-xs text-content-primary font-medium leading-relaxed">
                You retain complete and unencumbered intellectual property ownership of all schemas, DDL scripts, migration files, Prisma definitions, EF Core models, and documentation generated by or exported from Namines.
              </p>
              <ul className="list-disc pl-5 space-y-1.5 text-xs text-content-muted">
                <li>Namines asserts no patent, copyright, or licensing claims over your data architectures.</li>
                <li>You may freely export, fork, modify, and run all generated DDL scripts on any infrastructure without ongoing subscription requirements or proprietary runtime dependencies.</li>
                <li>We do not train general-purpose foundational AI models on your private schema definitions.</li>
              </ul>
            </div>
          </section>

          {/* Section 3: Acceptable Use */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-content-primary tracking-tight">
              3. Acceptable Use Policy
            </h2>
            <p>You agree not to misuse the Namines platform. Specifically, you agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 text-xs text-content-muted">
              <li>
                Attempt to break out of, exploit, or disrupt our ephemeral container sandboxes or test runners.
              </li>
              <li>
                Probe, scan, or attack loopback addresses, private subnets (RFC-1918), or cloud metadata services via our introspection endpoints (which are protected by our automated Zero SSRF firewall).
              </li>
              <li>
                Reverse engineer, decompile, or attempt to derive the proprietary algorithmic models of the Schema Impact Analyzer or control plane dispatchers.
              </li>
              <li>
                Exceed automated rate limits or intentionally saturate shared provisioning queues through automated denial-of-service scripts.
              </li>
            </ul>
          </section>

          {/* Section 4: Deterministic Guarantees & Safety */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-content-primary tracking-tight flex items-center gap-2">
              <FileCheck className="w-5 h-5 text-accent-text" />
              <span>4. Deterministic Validation &amp; Production Migrations</span>
            </h2>
            <p>
              Namines executes deterministic syntactic checks and provides risk classifications (Safe, Warning, Destructive) for suggested schema alterations. However:
            </p>
            <div className="rounded-[var(--radius-card)] border border-surface-500 bg-surface-800/40 p-5 space-y-2 text-xs text-content-muted">
              <div className="flex items-center gap-2 text-content-primary font-semibold">
                <AlertCircle className="w-4 h-4 text-accent-text" />
                <span>Production Staging &amp; Backup Responsibility</span>
              </div>
              <p className="leading-relaxed">
                While Namines provides ephemerally validated migrations, database state and live table sizes in production environments can introduce table locks or transaction timeouts. Users remain responsible for backing up production data and reviewing migration scripts in a dedicated staging environment prior to executing Destructive alterations.
              </p>
            </div>
          </section>

          {/* Section 5: Subprocessors */}
          <section id="subprocessors" className="space-y-4">
            <h2 className="text-xl font-bold text-content-primary tracking-tight">
              5. Authorized Subprocessors
            </h2>
            <p>
              Namines engages select third-party infrastructure subprocessors to provide cloud services and hosting:
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono border-collapse border border-surface-500">
                <thead>
                  <tr className="bg-surface-800 text-content-primary border-b border-surface-500">
                    <th className="p-3">Subprocessor</th>
                    <th className="p-3">Service Role</th>
                    <th className="p-3">Location</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-surface-500/60 text-content-muted">
                  <tr>
                    <td className="p-3 font-semibold text-content-primary">Amazon Web Services (AWS)</td>
                    <td className="p-3">Core Cloud Hosting &amp; Secret Key Storage (KMS)</td>
                    <td className="p-3">United States &amp; EU</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-content-primary">Cloudflare, Inc.</td>
                    <td className="p-3">Edge CDN, DDoS Mitigation &amp; DNS</td>
                    <td className="p-3">Global Edge</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-content-primary">PostHog, Inc.</td>
                    <td className="p-3">Aggregated Product Analytics (Self-hosted mode)</td>
                    <td className="p-3">EU Cloud</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          {/* Section 6: Limitation of Liability */}
          <section className="space-y-4 border-t border-surface-500/80 pt-8">
            <h2 className="text-xl font-bold text-content-primary tracking-tight">
              6. Limitation of Liability &amp; Contact
            </h2>
            <p className="text-xs text-content-muted leading-relaxed">
              To the maximum extent permitted by applicable law, Namines and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business interruption arising out of the use or inability to use the platform.
            </p>
            <p className="text-xs text-content-muted">
              Questions regarding these Terms of Service should be addressed to our legal department at:{' '}
              <a
                href="mailto:legal@namines.com"
                className="text-accent-text hover:underline font-mono"
              >
                legal@namines.com
              </a>
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </div>
  );
}
