using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.PrismaGenerator;

/// <summary>
/// <c>schema.prisma</c> üreticisi (new-phase/12-CODEGEN-EJECT.md).
///
/// Tasarım ilkesi DDL üreticileriyle aynı: <b>varsayılan asla sessiz kayba doğru
/// düşmez.</b> Prisma'da karşılığı olmayan her yapı (CHECK, kısmi index, INCLUDE,
/// index yöntemi) atılmaz — uyarı olarak bildirilir ve dosyanın başına yorum olarak
/// yazılır. Sebebi somut: kullanıcı bu dosyadan <c>prisma db push</c> çalıştırırsa,
/// şemada olmayan bir CHECK kısıtı veritabanından DÜŞER. Sessizce üretilen "çalışır
/// görünen" bir dosya, veriyi koruyan bir kısıtı yok edebilir.
/// </summary>
public class PrismaGeneratorService : IPrismaGenerator
{
    public PrismaGenerationResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        ArgumentNullException.ThrowIfNull(schema);

        var provider = Provider(engine);
        var warnings = new List<string>();

        var models = schema.Tables
            .Select(t => new ModelInfo(t, PrismaNaming.ToModelName(t.Name)))
            .ToList();

        DisambiguateModelNames(models);

        var relations = ResolveRelations(schema, models, warnings);

        var sb = new StringBuilder();
        AppendHeader(sb, schema, provider, engine);

        foreach (var model in models)
            AppendModel(sb, model, schema, engine, relations, warnings);

        // Uyarılar dosyanın BAŞINA yazılır: sonda olsalar, uzun bir şemada
        // görülmeden `prisma db push` çalıştırılırdı.
        var body = sb.ToString();
        var files = new Dictionary<string, string>
        {
            ["schema.prisma"] = WarningBanner(warnings) + body,
            [".env.example"] = EnvExample(provider),
        };

        return new PrismaGenerationResult(files, warnings);
    }

    // ── Motor → Prisma provider ──────────────────────────────────────────────

    private static string Provider(DatabaseType engine) => engine switch
    {
        DatabaseType.PostgreSQL => "postgresql",
        DatabaseType.MySQL => "mysql",
        // MariaDB'nin ayrı bir provider'ı yoktur; Prisma onu mysql üzerinden konuşur.
        DatabaseType.MariaDB => "mysql",
        DatabaseType.MSSQL => "sqlserver",
        DatabaseType.SQLite => "sqlite",

        // Prisma'nın Oracle desteği YOKTUR. Sessizce başka bir provider seçmek
        // (ör. postgresql) ayrıştırılabilir ama TAMAMEN YANLIŞ bir dosya üretirdi;
        // kullanıcı bunu ancak canlıda çalıştırınca fark ederdi.
        _ => throw new NotSupportedException(
            $"Prisma does not support {engine}. Supported: PostgreSQL, MySQL, MariaDB, SQL Server, SQLite. " +
            "Use the EF Core export or raw DDL for this engine instead.")
    };

    // ── Başlık ───────────────────────────────────────────────────────────────

    private static void AppendHeader(StringBuilder sb, DatabaseSchema schema, string provider, DatabaseType engine)
    {
        sb.AppendLine("// Generated by Namines.");
        if (!string.IsNullOrWhiteSpace(schema.Name))
            sb.AppendLine($"// Schema: {schema.Name}");
        sb.AppendLine($"// Engine: {engine}");
        sb.AppendLine();
        sb.AppendLine("generator client {");
        sb.AppendLine("  provider = \"prisma-client-js\"");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("datasource db {");
        sb.AppendLine($"  provider = \"{provider}\"");
        sb.AppendLine("  url      = env(\"DATABASE_URL\")");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string WarningBanner(IReadOnlyList<string> warnings)
    {
        if (warnings.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// -------------------------------------------------------------");
        sb.AppendLine("// WARNING: this schema is NOT a complete representation of your");
        sb.AppendLine("// database. Prisma cannot express the following, so they are");
        sb.AppendLine("// ABSENT below. Running `prisma db push` from this file would");
        sb.AppendLine("// DROP them from the database:");
        foreach (var warning in warnings) sb.AppendLine($"//   - {warning}");
        sb.AppendLine("// -------------------------------------------------------------");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EnvExample(string provider)
    {
        var sample = provider switch
        {
            "postgresql" => "postgresql://user:password@localhost:5432/mydb?schema=public",
            "mysql" => "mysql://user:password@localhost:3306/mydb",
            "sqlserver" => "sqlserver://localhost:1433;database=mydb;user=sa;password=password;encrypt=true",
            "sqlite" => "file:./dev.db",
            _ => "<connection string>"
        };
        return $"DATABASE_URL=\"{sample}\"\n";
    }

    // ── Model ────────────────────────────────────────────────────────────────

    private static void AppendModel(
        StringBuilder sb, ModelInfo model, DatabaseSchema schema, DatabaseType engine,
        List<RelationInfo> relations, List<string> warnings)
    {
        var table = model.Table;
        sb.AppendLine($"model {model.Name} {{");

        var pkColumns = table.Columns.Where(c => c.IsPK).ToList();
        var fieldNames = BuildFieldNames(table);

        foreach (var column in table.Columns)
            AppendScalarField(sb, column, fieldNames[column], pkColumns, engine);

        // İlişki alanları
        foreach (var relation in relations.Where(r => r.SourceModel == model))
            AppendOwningRelationField(sb, relation, fieldNames);

        foreach (var relation in relations.Where(r => r.TargetModel == model))
            sb.AppendLine($"  {relation.BackFieldName} {relation.SourceModel.Name}[]{RelationName(relation)}");

        AppendBlockAttributes(sb, model, schema, engine, pkColumns, fieldNames, warnings);

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendScalarField(
        StringBuilder sb, SchemaColumn column, string fieldName,
        List<SchemaColumn> pkColumns, DatabaseType engine)
    {
        var (scalar, native) = PrismaTypeMap.Map(column.Type, column.Length, engine);

        // Bileşik PK'da kolonlar tek tek nullable olamaz; @@id ile blok sonunda tanımlanır.
        var isSinglePk = column.IsPK && pkColumns.Count == 1;
        var optional = column.IsNullable && !column.IsPK ? "?" : string.Empty;

        var attributes = new List<string>();
        if (isSinglePk) attributes.Add("@id");

        if (isSinglePk && scalar is "Int" or "BigInt" && string.IsNullOrWhiteSpace(column.DefaultValue))
            // DDL üreticileri tekil tamsayı PK için SERIAL/IDENTITY yazıyor; Prisma
            // tarafında karşılığı bu. Eşleşmezse `prisma db push` sütunu yeniden yazar.
            attributes.Add("@default(autoincrement())");
        else if (!string.IsNullOrWhiteSpace(column.DefaultValue))
        {
            var mapped = MapDefault(column.DefaultValue!, scalar);
            if (mapped is not null) attributes.Add(mapped);
        }

        if (native is not null) attributes.Add(native);

        if (!string.Equals(fieldName, column.Name, StringComparison.Ordinal))
            attributes.Add($"@map(\"{PrismaNaming.Escape(column.Name)}\")");

        var suffix = attributes.Count > 0 ? " " + string.Join(" ", attributes) : string.Empty;
        sb.AppendLine($"  {fieldName} {scalar}{optional}{suffix}");
    }

    private static void AppendOwningRelationField(
        StringBuilder sb, RelationInfo relation, Dictionary<SchemaColumn, string> fieldNames)
    {
        var fkField = fieldNames[relation.SourceColumn];
        var targetField = PrismaNaming.ToFieldName(relation.TargetColumn.Name);
        var optional = relation.SourceColumn.IsNullable ? "?" : string.Empty;

        var parts = new List<string>
        {
            $"fields: [{fkField}]",
            $"references: [{targetField}]"
        };

        var onDelete = ReferentialActionName(relation.Relation.OnDelete);
        var onUpdate = ReferentialActionName(relation.Relation.OnUpdate);
        if (onDelete is not null) parts.Add($"onDelete: {onDelete}");
        if (onUpdate is not null) parts.Add($"onUpdate: {onUpdate}");

        var name = relation.RelationName is null ? string.Empty : $"\"{relation.RelationName}\", ";

        sb.AppendLine(
            $"  {relation.OwningFieldName} {relation.TargetModel.Name}{optional} " +
            $"@relation({name}{string.Join(", ", parts)})");
    }

    private static void AppendBlockAttributes(
        StringBuilder sb, ModelInfo model, DatabaseSchema schema, DatabaseType engine,
        List<SchemaColumn> pkColumns, Dictionary<SchemaColumn, string> fieldNames,
        List<string> warnings)
    {
        var table = model.Table;
        var wroteAny = false;

        void Blank()
        {
            if (!wroteAny) sb.AppendLine();
            wroteAny = true;
        }

        if (pkColumns.Count > 1)
        {
            Blank();
            sb.AppendLine($"  @@id([{string.Join(", ", pkColumns.Select(c => fieldNames[c]))}])");
        }

        foreach (var unique in table.Uniques)
        {
            var columns = unique.ColumnIds
                .Select(id => table.Columns.FirstOrDefault(c => c.Id == id))
                .Where(c => c is not null)
                .Select(c => fieldNames[c!])
                .ToList();

            if (columns.Count == 0) continue;
            Blank();
            sb.AppendLine($"  @@unique([{string.Join(", ", columns)}]{MapName(unique.Name)})");
        }

        foreach (var index in table.Indexes)
        {
            var columns = index.Columns
                .Select(ic => table.Columns.FirstOrDefault(c => c.Id == ic.ColumnId))
                .Where(c => c is not null)
                .Select(c => fieldNames[c!])
                .ToList();

            if (columns.Count == 0) continue;

            // Prisma'da karşılığı olmayan index özellikleri. Sessizce düşürmek,
            // üretilen şemanın performans davranışını sessizce değiştirirdi.
            if (!string.IsNullOrWhiteSpace(index.Where))
                warnings.Add($"{table.Name}: partial index condition \"{index.Where}\" (Prisma has no partial-index support)");

            if (index.IncludeColumnIds.Count > 0)
                warnings.Add($"{table.Name}: covering index INCLUDE columns (Prisma has no INCLUDE support)");

            if (!string.IsNullOrWhiteSpace(index.Method) &&
                !index.Method.Equals("btree", StringComparison.OrdinalIgnoreCase) &&
                engine != DatabaseType.PostgreSQL)
                warnings.Add($"{table.Name}: index method \"{index.Method}\" is not expressible for this provider");

            var attribute = index.IsUnique ? "@@unique" : "@@index";
            var typeArg = string.Empty;
            if (engine == DatabaseType.PostgreSQL && !string.IsNullOrWhiteSpace(index.Method) &&
                !index.Method.Equals("btree", StringComparison.OrdinalIgnoreCase))
                typeArg = $", type: {Capitalize(index.Method!)}";

            Blank();
            sb.AppendLine($"  {attribute}([{string.Join(", ", columns)}]{typeArg}{MapName(index.Name)})");
        }

        // CHECK kısıtları: Prisma'da HİÇBİR karşılığı yok. En kritik uyarı bu —
        // kısıtın kaybı veri bütünlüğünün kaybıdır.
        foreach (var check in table.Checks.Where(c => !string.IsNullOrWhiteSpace(c.Expression)))
            warnings.Add($"{table.Name}: CHECK constraint \"{check.Expression}\" (Prisma cannot express CHECK constraints)");

        if (!string.Equals(model.Name, table.Name, StringComparison.Ordinal))
        {
            Blank();
            sb.AppendLine($"  @@map(\"{PrismaNaming.Escape(table.Name)}\")");
        }
    }

    /// <summary>
    /// <c>map:</c> argümanı parantezin İÇİNE yazılır. Dışına yazmak
    /// (<c>@@unique([x]), map: "y"</c>) Prisma'da "not a valid field or attribute
    /// definition" hatası verir — gerçek <c>prisma validate</c> testi bunu yakaladı,
    /// metin iddiaları yakalayamamıştı.
    /// </summary>
    private static string MapName(string? name) =>
        string.IsNullOrWhiteSpace(name) ? string.Empty : $", map: \"{PrismaNaming.Escape(name)}\"";

    private static string Capitalize(string value) =>
        value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value[1..].ToLowerInvariant();

    /// <summary>
    /// Prisma varsayılanı NoAction ile aynı davranmaz mı? Hayır — Prisma, zorunlu
    /// ilişkilerde varsayılan olarak <c>Restrict</c>, opsiyonellerde <c>SetNull</c>
    /// uygular. Bu yüzden NoAction dahil TÜM eylemler açıkça yazılır; boş bırakmak
    /// veritabanındakinden farklı bir davranış üretirdi.
    /// </summary>
    private static string? ReferentialActionName(ReferentialAction action) => action switch
    {
        ReferentialAction.NoAction => "NoAction",
        ReferentialAction.Restrict => "Restrict",
        ReferentialAction.Cascade => "Cascade",
        ReferentialAction.SetNull => "SetNull",
        ReferentialAction.SetDefault => "SetDefault",
        _ => null
    };

    private static string RelationName(RelationInfo relation) =>
        relation.RelationName is null ? string.Empty : $" @relation(\"{relation.RelationName}\")";

    /// <summary>
    /// Ham SQL default'unu Prisma'ya çevirir. ÇEVİRİLEMİYORSA null döner ve default
    /// hiç yazılmaz: uydurma bir değer yazmak, sütunun gerçek varsayılanını sessizce
    /// değiştirmek olurdu.
    /// </summary>
    private static string? MapDefault(string raw, string scalar)
    {
        var value = raw.Trim();

        if (value.Equals("CURRENT_TIMESTAMP", StringComparison.OrdinalIgnoreCase) ||
            value.Equals("NOW()", StringComparison.OrdinalIgnoreCase) ||
            value.Equals("GETDATE()", StringComparison.OrdinalIgnoreCase))
            return "@default(now())";

        if (value.Equals("NEWID()", StringComparison.OrdinalIgnoreCase) ||
            value.Equals("GEN_RANDOM_UUID()", StringComparison.OrdinalIgnoreCase) ||
            value.Equals("UUID()", StringComparison.OrdinalIgnoreCase))
            return "@default(uuid())";

        if (scalar == "Boolean")
        {
            if (value is "1" || value.Equals("TRUE", StringComparison.OrdinalIgnoreCase)) return "@default(true)";
            if (value is "0" || value.Equals("FALSE", StringComparison.OrdinalIgnoreCase)) return "@default(false)";
            return null;
        }

        if (scalar is "Int" or "BigInt" or "Float" or "Decimal")
            return decimal.TryParse(value, System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture, out var number)
                ? $"@default({number.ToString(System.Globalization.CultureInfo.InvariantCulture)})"
                : null;

        if (scalar == "String")
        {
            var unquoted = value.Trim('\'', '"');
            // Fonksiyon çağrısı ya da ifade gibi görünüyorsa dize sanıp tırnaklama.
            if (unquoted.Contains('(') || unquoted.Contains(')')) return null;
            return $"@default(\"{PrismaNaming.Escape(unquoted)}\")";
        }

        return null;
    }

    // ── İlişkiler ────────────────────────────────────────────────────────────

    private static List<RelationInfo> ResolveRelations(
        DatabaseSchema schema, List<ModelInfo> models, List<string> warnings)
    {
        var byTableId = models.ToDictionary(m => m.Table.Id, m => m, StringComparer.Ordinal);
        var resolved = new List<RelationInfo>();

        foreach (var relation in schema.Relations ?? new List<SchemaRelation>())
        {
            if (!byTableId.TryGetValue(relation.SourceTableId ?? string.Empty, out var source) ||
                !byTableId.TryGetValue(relation.TargetTableId ?? string.Empty, out var target))
                continue;

            var sourceColumn = source.Table.Columns.FirstOrDefault(c => c.Id == relation.SourceColumnId);
            var targetColumn = target.Table.Columns.FirstOrDefault(c => c.Id == relation.TargetColumnId);
            if (sourceColumn is null || targetColumn is null) continue;

            resolved.Add(new RelationInfo(relation, source, sourceColumn, target, targetColumn));
        }

        AssignRelationFieldNames(resolved, warnings);
        return resolved;
    }

    /// <summary>
    /// Alan adlarını atar ve çakışmaları giderir.
    ///
    /// Aynı iki model arasında birden fazla ilişki varsa (klasik örnek: bir mesajın
    /// <c>senderId</c> ve <c>recipientId</c> alanlarının ikisi de <c>User</c>'a
    /// bakması) Prisma <b>adlandırılmış ilişki</b> ŞART KOŞAR — yoksa şema
    /// ayrıştırılamaz. Bu, üretilen dosyanın hiç derlenmemesi demektir.
    /// </summary>
    private static void AssignRelationFieldNames(List<RelationInfo> relations, List<string> warnings)
    {
        foreach (var group in relations.GroupBy(r => (r.SourceModel.Name, r.TargetModel.Name)))
        {
            var list = group.ToList();
            var ambiguous = list.Count > 1;

            foreach (var relation in list)
            {
                // Ad çakışmasını FK kolon adından türeterek çöz: senderId → sender.
                var baseName = StripIdSuffix(relation.SourceColumn.Name);
                relation.OwningFieldName = ambiguous
                    ? PrismaNaming.ToFieldName(baseName)
                    : PrismaNaming.ToFieldName(relation.TargetModel.Table.Name);

                relation.BackFieldName = ambiguous
                    ? PrismaNaming.ToPluralFieldName($"{baseName}_{relation.SourceModel.Table.Name}")
                    : PrismaNaming.ToPluralFieldName(relation.SourceModel.Table.Name);

                if (ambiguous)
                    relation.RelationName = $"{relation.SourceModel.Name}_{PrismaNaming.ToModelName(baseName)}";
            }

            // Türetme yine de çakıştıysa (ör. iki FK aynı ada indirgeniyorsa) sessizce
            // geçersiz şema üretmek yerine sonek ekle ve durumu bildir.
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var relation in list)
            {
                var candidate = relation.OwningFieldName;
                var suffix = 2;
                while (!seen.Add(candidate))
                    candidate = relation.OwningFieldName + suffix++;

                if (!string.Equals(candidate, relation.OwningFieldName, StringComparison.Ordinal))
                {
                    warnings.Add(
                        $"{relation.SourceModel.Table.Name}: two relations produced the same field name; " +
                        $"renamed one to \"{candidate}\"");
                    relation.OwningFieldName = candidate;
                }
            }
        }
    }

    private static string StripIdSuffix(string columnName)
    {
        foreach (var suffix in new[] { "_id", "Id", "_ID", "ID" })
        {
            if (columnName.Length > suffix.Length &&
                columnName.EndsWith(suffix, StringComparison.Ordinal))
                return columnName[..^suffix.Length];
        }
        return columnName;
    }

    /// <summary>
    /// Kolon → Prisma alan adı. Aynı model içinde iki kolon aynı ada indirgenirse
    /// (ör. <c>user_id</c> ve <c>userId</c>) şema ayrıştırılamaz; sonekle ayrılır.
    /// </summary>
    private static Dictionary<SchemaColumn, string> BuildFieldNames(SchemaTable table)
    {
        var result = new Dictionary<SchemaColumn, string>();
        var used = new HashSet<string>(StringComparer.Ordinal);

        foreach (var column in table.Columns)
        {
            var name = PrismaNaming.ToFieldName(column.Name);
            var candidate = name;
            var suffix = 2;
            while (!used.Add(candidate)) candidate = name + suffix++;
            result[column] = candidate;
        }
        return result;
    }

    private static void DisambiguateModelNames(List<ModelInfo> models)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in models)
        {
            var candidate = model.Name;
            var suffix = 2;
            while (!used.Add(candidate)) candidate = model.Name + suffix++;
            model.Name = candidate;
        }
    }

    private sealed class ModelInfo
    {
        public ModelInfo(SchemaTable table, string name)
        {
            Table = table;
            Name = name;
        }

        public SchemaTable Table { get; }
        public string Name { get; set; }
    }

    private sealed class RelationInfo
    {
        public RelationInfo(
            SchemaRelation relation, ModelInfo sourceModel, SchemaColumn sourceColumn,
            ModelInfo targetModel, SchemaColumn targetColumn)
        {
            Relation = relation;
            SourceModel = sourceModel;
            SourceColumn = sourceColumn;
            TargetModel = targetModel;
            TargetColumn = targetColumn;
        }

        public SchemaRelation Relation { get; }
        public ModelInfo SourceModel { get; }
        public SchemaColumn SourceColumn { get; }
        public ModelInfo TargetModel { get; }
        public SchemaColumn TargetColumn { get; }

        public string OwningFieldName { get; set; } = string.Empty;
        public string BackFieldName { get; set; } = string.Empty;
        public string? RelationName { get; set; }
    }
}
