using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Namines.Core.Analysis;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>console.nextjs</c> — 07 §8. Şemadan çalışan bir admin paneli.
///
/// Panel Gateway'e API ANAHTARIYLA konuşuyor, veritabanına doğrudan DEĞİL. İki
/// sebep: (1) bağlantı dizesi tarayıcıya inmez, (2) Gateway'in tablo izinleri ve
/// PII maskelemesi panelde de geçerli olur — panel ayrı bir güvenlik yüzeyi açmaz.
///
/// <b>Dokümandan sapma, bilinçli:</b> 07 §8 "Next.js 16 + shadcn/ui + TanStack
/// Table" diyor. Üretilen paket bunları KULLANMIYOR; düz React + inline stil.
/// Sebep: shadcn kurulumu ayrı bir CLI adımı (<c>npx shadcn init</c>) ve onlarca
/// dosya ister, TanStack Table da ek bir bağımlılık. Kutudan çıktığı gibi
/// <c>npm install &amp;&amp; npm run dev</c> ile ÇALIŞAN bir panel, kurulum adımı
/// gerektiren "daha güzel" bir panelden iyidir. Kullanıcı isterse üstüne kurar —
/// çıktı gerçek kaynak kod, kilit yok.
/// </summary>
public sealed class ConsoleNextjsGenerator : IEjectGenerator
{
    public string Target => "console.nextjs";
    public string DisplayName => "Admin console (Next.js)";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        var metadata = ConsoleMetadata.Describe(schema);

        foreach (var table in metadata.Where(m => m.Pattern == PagePattern.ReadOnly))
            warnings.Add(
                $"{table.Table.Name}: no primary key, so the console can only list rows — " +
                "editing needs a key to target a single row safely.");

        foreach (var table in metadata.Where(m => m.Pattern == PagePattern.Junction))
            warnings.Add(
                $"{table.Table.Name}: detected as a junction table. It is listed but has no " +
                "dedicated editor; relationship editing is not generated yet.");

        if (schema.Tables.Any(t => t.Checks.Any(c => !string.IsNullOrWhiteSpace(c.Expression))))
            warnings.Add(
                "CHECK constraints are not enforced in the generated forms. The database still " +
                "rejects invalid values, but the user sees the error only after saving.");

        // Sessiz kalirsa kullanici bunu ancak verisi yanlis yazildiktan sonra fark eder.
        if (metadata.Any(m => m.Pattern != PagePattern.ReadOnly &&
                              m.Table.Columns.Any(c => c.IsNullable &&
                                                       CanonicalType.Classify(c.Type) == TypeKind.Text)))
            warnings.Add(
                "In the generated forms an empty box on a nullable column is saved as NULL, not " +
                "as an empty string. That makes clearing a field possible; the trade-off is that " +
                "a nullable text column cannot be set to \"\" from the console.");

        if (metadata.Any(m => m.Pattern != PagePattern.ReadOnly && m.PrimaryKey is not null))
            warnings.Add(
                "The console cannot tell from the schema whether a primary key is generated by " +
                "the database. Leaving the key box empty omits the column entirely, which lets " +
                "the database assign it; filling it in sends the value you typed.");

        var files = new Dictionary<string, string>
        {
            ["package.json"] = PackageJson(schema),
            [".env.example"] = EnvExample(),
            ["README.md"] = Readme(schema, metadata),
            ["next.config.mjs"] = "export default {};\n",
            ["tsconfig.json"] = TsConfig(),
            ["lib/types.ts"] = new TypeScriptTypesGenerator().Generate(schema, engine).Files["types.ts"],
            ["lib/schema.ts"] = SchemaMetadata(metadata),
            ["lib/gateway.ts"] = GatewayClient(),
            ["app/layout.tsx"] = Layout(schema),
            ["app/page.tsx"] = IndexPage(),
            ["app/[table]/page.tsx"] = TablePage(),
            ["app/actions.ts"] = ServerActions(),
            ["app/[table]/new/page.tsx"] = NewRowPage(),
            ["app/[table]/[id]/page.tsx"] = EditRowPage(),
            ["components/RowForm.tsx"] = RowFormComponent(),
            ["components/DeleteButton.tsx"] = DeleteButtonComponent(),
        };

        return new EjectResult(files, warnings);
    }

    private static string PackageJson(DatabaseSchema schema)
    {
        var name = FlywayGenerator.Sanitize(schema.Name) + "-console";
        return $$"""
        {
          "name": "{{name}}",
          "private": true,
          "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start"
          },
          "dependencies": {
            "next": "^15.0.0",
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
          },
          "devDependencies": {
            "@types/node": "^20.0.0",
            "@types/react": "^19.0.0",
            "typescript": "^5.5.0"
          }
        }

        """;
    }

    private static string EnvExample() => """
        # The Namines Gateway this console talks to.
        NAMINES_API_URL=http://localhost:5000

        # A Gateway API key with read (and, if you want editing, write) permission
        # on the tables below. Create one in Namines under Review > Gateway API keys.
        #
        # This variable is NOT prefixed with NEXT_PUBLIC_ on purpose: the key stays
        # on the server. Exposing it to the browser would hand every visitor full
        # access to the tables it can reach.
        NAMINES_API_KEY=nmn_replace_me

        """;

    private static string TsConfig() => """
        {
          "compilerOptions": {
            "target": "ES2022",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": true,
            "skipLibCheck": true,
            "strict": true,
            "noEmit": true,
            "esModuleInterop": true,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": true,
            "isolatedModules": true,
            "jsx": "preserve",
            "incremental": true,
            "plugins": [{ "name": "next" }],
            "paths": { "@/*": ["./*"] }
          },
          "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          "exclude": ["node_modules"]
        }

        """;

    private static string Readme(DatabaseSchema schema, IReadOnlyList<TableMetadata> metadata)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {schema.Name} — admin console");
        sb.AppendLine();
        sb.AppendLine("Generated by Namines from your schema. This is real source code: change");
        sb.AppendLine("anything you like, it will keep working without Namines.");
        sb.AppendLine();
        sb.AppendLine("## Run it");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("cp .env.example .env.local   # then fill in NAMINES_API_KEY");
        sb.AppendLine("npm install");
        sb.AppendLine("npm run dev");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## How it talks to your data");
        sb.AppendLine();
        sb.AppendLine("The console calls the Namines Gateway, not your database directly. That");
        sb.AppendLine("means the API key's table permissions and PII masking apply here too — the");
        sb.AppendLine("console cannot reach anything the key cannot.");
        sb.AppendLine();
        sb.AppendLine("The key is read on the **server** only. It is never sent to the browser.");
        sb.AppendLine();
        sb.AppendLine("## Editing rows");
        sb.AppendLine();
        sb.AppendLine("Create, edit and delete run as **server actions**, so the API key never");
        sb.AppendLine("leaves the server and there is no extra endpoint of your own to protect.");
        sb.AppendLine();
        sb.AppendLine("Three behaviours are worth knowing before you use them:");
        sb.AppendLine();
        sb.AppendLine("- **An empty box on a nullable column saves NULL**, not an empty string.");
        sb.AppendLine("  Otherwise a field could never be cleared once it had a value. The");
        sb.AppendLine("  trade-off: a nullable text column cannot be set to `\"\"` from here.");
        sb.AppendLine("- **Leave the key empty when the database generates it.** The column is then");
        sb.AppendLine("  left out of the insert entirely. The schema does not record whether a key");
        sb.AppendLine("  is auto-generated, so the console cannot decide this for you.");
        sb.AppendLine("- **The key is read-only when editing.** It is how the row is found; letting");
        sb.AppendLine("  you change it in the same request would describe two rows at once.");
        sb.AppendLine();
        sb.AppendLine("Deleting asks for confirmation and names the row. There is no undo behind");
        sb.AppendLine("it — the Gateway runs a real `DELETE` against your database. The Gateway");
        sb.AppendLine("refuses and rolls back if a write would touch more than one row.");
        sb.AppendLine();
        sb.AppendLine("## Pages");
        sb.AppendLine();
        sb.AppendLine("| Table | Pattern |");
        sb.AppendLine("|---|---|");
        foreach (var table in metadata)
            sb.AppendLine($"| `{table.Table.Name}` | {table.Pattern} |");
        sb.AppendLine();
        sb.AppendLine("Patterns are chosen automatically from the schema shape: a table with no");
        sb.AppendLine("primary key is read-only, a table whose composite key is entirely foreign");
        sb.AppendLine("keys is a junction, a table referencing itself is a tree.");
        return sb.ToString();
    }

    /// <summary>
    /// Şema meta verisi VERİ olarak gömülüyor, sayfa başına kod olarak değil.
    ///
    /// 40 tablolu bir şemada 40 ayrı sayfa üretmek, kullanıcının bakımını yapacağı
    /// kod miktarını 40 katına çıkarır. Tek bir dinamik sayfa + veri, aynı işi
    /// yapıp değiştirilebilir kalıyor.
    /// </summary>
    private static string SchemaMetadata(IReadOnlyList<TableMetadata> metadata)
    {
        var payload = metadata.Select(m => new
        {
            name = m.Table.Name,
            pattern = m.Pattern.ToString().ToLowerInvariant(),
            primaryKey = m.PrimaryKey?.Name,
            labelColumn = m.LabelColumn?.Name,
            columns = m.Table.Columns.Select(c => new
            {
                name = c.Name,
                widget = ConsoleMetadata.Widget(c),
                nullable = c.IsNullable,
                isPrimaryKey = c.IsPK,
                // Değeri veritabanı üretiyorsa kullanıcıdan istemenin anlamı yok.
                // G40'ta bu bilgi modelde YOKTU ve form "anahtarı boş bırak"
                // diye yazılı bir nota mecbur kalmıştı; artık form biliyor.
                isGenerated = IdentityPolicy.IsGenerated(m.Table, c),
                maxLength = c.Length,
            }),
        });

        var json = JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });

        return $$"""
        // Generated by Namines. Do not edit by hand.

        export interface ConsoleColumn {
          name: string;
          widget: string;
          nullable: boolean;
          isPrimaryKey: boolean;
          /** The database assigns this value; the form does not ask for it. */
          isGenerated: boolean;
          maxLength: number | null;
        }

        export interface ConsoleTable {
          name: string;
          pattern: "crud" | "junction" | "tree" | "readonly";
          primaryKey: string | null;
          labelColumn: string | null;
          columns: ConsoleColumn[];
        }

        export const tables: ConsoleTable[] = {{json}};

        export function findTable(name: string): ConsoleTable | undefined {
          return tables.find((t) => t.name === name);
        }

        """;
    }

    private static string GatewayClient() => """
        // Generated by Namines. Do not edit by hand.
        //
        // Server-only: this module reads NAMINES_API_KEY. Importing it from a client
        // component would ship the key to the browser, so it is marked accordingly.
        import "server-only";

        const baseUrl = process.env.NAMINES_API_URL ?? "http://localhost:5000";
        const apiKey = process.env.NAMINES_API_KEY ?? "";

        export interface ListResult<T> {
          rows: T[];
          page: number;
          pageSize: number;
          totalCount: number;
        }

        /**
         * The Gateway wraps every row as `{ values: { ... } }` so it can add row-level
         * metadata later without breaking clients. The console does not need that
         * envelope, and unwrapping it here — rather than in each page — keeps the
         * shape in one place.
         */
        interface WrappedRow<T> {
          values: T;
        }

        async function call<T>(path: string, body: unknown): Promise<T> {
          if (!apiKey) {
            throw new Error(
              "NAMINES_API_KEY is not set. Copy .env.example to .env.local and fill it in."
            );
          }

          const response = await fetch(`${baseUrl}/api/gateway/${path}`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-Namines-Key": apiKey,
            },
            body: JSON.stringify(body),
            // Admin console: always show current data, never a cached page.
            cache: "no-store",
          });

          if (!response.ok) {
            // The Gateway explains refusals precisely (permission, rate limit,
            // origin). Passing the message through is more useful than a generic
            // "request failed".
            const detail = await response.text();
            throw new Error(`Gateway ${response.status}: ${detail}`);
          }

          return (await response.json()) as T;
        }

        /**
         * The connection string lives on this server, not in Namines: the Gateway
         * needs it per request. Keep it beside the API key.
         */
        function connection() {
          const value = process.env.NAMINES_DB_CONNECTION;
          if (!value) {
            throw new Error(
              "NAMINES_DB_CONNECTION is not set. It is the connection string the Gateway uses."
            );
          }
          return value;
        }

        export async function listRows<T>(
          tableName: string,
          page = 1,
          pageSize = 25,
          orderByColumn?: string | null
        ): Promise<ListResult<T>> {
          const result = await call<ListResult<WrappedRow<T>>>("list", {
            connectionString: connection(),
            dbType: process.env.NAMINES_DB_TYPE ?? "PostgreSQL",
            tableName,
            page,
            pageSize,
            orderByColumn,
          });

          return { ...result, rows: result.rows.map((row) => row.values) };
        }

        export async function detailRow<T>(
          tableName: string,
          pkColumn: string,
          pkValue: string
        ): Promise<T | null> {
          const result = await call<WrappedRow<T> | null>("detail", {
            connectionString: connection(),
            dbType: process.env.NAMINES_DB_TYPE ?? "PostgreSQL",
            tableName,
            pkColumn,
            pkValue,
          });

          return result ? result.values : null;
        }

        /**
         * Values are sent as strings; `null` means SQL NULL. The Gateway binds them
         * as parameters, so nothing here is concatenated into SQL.
         */
        export function createRow(tableName: string, values: Record<string, string | null>) {
          return call<Record<string, unknown>>("create", {
            connectionString: connection(),
            dbType: process.env.NAMINES_DB_TYPE ?? "PostgreSQL",
            tableName,
            values,
          });
        }

        export function updateRow(
          tableName: string,
          pkColumn: string,
          pkValue: string,
          values: Record<string, string | null>
        ) {
          return call<{ affectedRows: number }>("update", {
            connectionString: connection(),
            dbType: process.env.NAMINES_DB_TYPE ?? "PostgreSQL",
            tableName,
            pkColumn,
            pkValue,
            values,
          });
        }

        export function deleteRow(tableName: string, pkColumn: string, pkValue: string) {
          return call<{ affectedRows: number }>("delete", {
            connectionString: connection(),
            dbType: process.env.NAMINES_DB_TYPE ?? "PostgreSQL",
            tableName,
            pkColumn,
            pkValue,
          });
        }

        """;

    /// <summary>
    /// Ham dize + Replace kullanılıyor, interpolasyon DEĞİL: JSX'te <c>style={{...}}</c>
    /// çift süslü parantez taşır ve C#'ın <c>$$</c> interpolasyon sınırlayıcısıyla
    /// çakışır (derleme hatası). Yer tutucu değiştirmek bu çakışmayı tamamen
    /// ortadan kaldırıyor.
    /// </summary>
    private static string Layout(DatabaseSchema schema) => """
        // Generated by Namines. Do not edit by hand.
        import type { ReactNode } from "react";
        import Link from "next/link";
        import { tables } from "../lib/schema";

        export const metadata = { title: "__SCHEMA_NAME__ — console" };

        export default function RootLayout({ children }: { children: ReactNode }) {
          return (
            <html lang="en">
              <body style={{ margin: 0, fontFamily: "system-ui, sans-serif", display: "flex" }}>
                <nav
                  style={{
                    width: 220,
                    minHeight: "100vh",
                    borderRight: "1px solid #e5e7eb",
                    padding: "16px 12px",
                  }}
                >
                  <Link href="/" style={{ fontWeight: 600, textDecoration: "none", color: "#111827" }}>
                    __SCHEMA_NAME__
                  </Link>
                  <ul style={{ listStyle: "none", padding: 0, marginTop: 16 }}>
                    {tables.map((table) => (
                      <li key={table.name} style={{ margin: "4px 0" }}>
                        <Link
                          href={`/${table.name}`}
                          style={{ textDecoration: "none", color: "#374151", fontSize: 14 }}
                        >
                          {table.name}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </nav>
                <main style={{ flex: 1, padding: 24, minWidth: 0 }}>{children}</main>
              </body>
            </html>
          );
        }

        """.Replace("__SCHEMA_NAME__", schema.Name);

    private static string IndexPage() => """
        // Generated by Namines. Do not edit by hand.
        import Link from "next/link";
        import { tables } from "../lib/schema";

        export default function Home() {
          return (
            <div>
              <h1 style={{ fontSize: 20, marginTop: 0 }}>Tables</h1>
              <table style={{ borderCollapse: "collapse", fontSize: 14 }}>
                <thead>
                  <tr>
                    <th style={{ textAlign: "left", padding: "6px 12px" }}>Table</th>
                    <th style={{ textAlign: "left", padding: "6px 12px" }}>Pattern</th>
                    <th style={{ textAlign: "left", padding: "6px 12px" }}>Columns</th>
                  </tr>
                </thead>
                <tbody>
                  {tables.map((table) => (
                    <tr key={table.name} style={{ borderTop: "1px solid #e5e7eb" }}>
                      <td style={{ padding: "6px 12px" }}>
                        <Link href={`/${table.name}`}>{table.name}</Link>
                      </td>
                      <td style={{ padding: "6px 12px", color: "#6b7280" }}>{table.pattern}</td>
                      <td style={{ padding: "6px 12px", color: "#6b7280" }}>{table.columns.length}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          );
        }

        """;


    /// <summary>
    /// Yazma yolu Server Action olarak uretiliyor, istemciden cagrilan bir API
    /// route olarak DEGIL.
    ///
    /// <b>Sebep API anahtari.</b> Panelin anahtari yalnizca sunucuda duruyor; yazma
    /// islemini tarayicidan yapmak, ya anahtari tarayiciya indirmek ya da anahtari
    /// koruyan ikinci bir uc yazmak demekti. Server Action ikisini de gerektirmiyor:
    /// form dogrudan sunucudaki fonksiyona gidiyor.
    /// </summary>
    private static string ServerActions() => """
        // Generated by Namines. Do not edit by hand.
        "use server";

        import { revalidatePath } from "next/cache";
        import { redirect } from "next/navigation";
        import { findTable, type ConsoleTable } from "../lib/schema";
        import { createRow, updateRow, deleteRow } from "../lib/gateway";

        export interface FormState {
          error: string | null;
        }

        /**
         * Reads a submitted form into the value map the Gateway expects.
         *
         * An empty input on a **nullable** column becomes SQL NULL, not "". If both
         * became "", a nullable column could never be cleared once it held a value --
         * and clearing a field is one of the things an admin console exists for. The
         * cost: a nullable text column cannot be set to an empty string from this
         * form. That is the rarer need, and the README says so.
         *
         * The primary key is excluded on update: the key identifies which row to
         * change, so allowing it in the same payload would let one field mean two
         * different things at once.
         */
        function readValues(
          table: ConsoleTable,
          form: FormData,
          options: { includePrimaryKey: boolean }
        ): Record<string, string | null> {
          const values: Record<string, string | null> = {};

          for (const column of table.columns) {
            if (column.isPrimaryKey && !options.includePrimaryKey) continue;

            const raw = form.get(column.name);
            if (raw === null) continue;

            const text = String(raw);

            if (text === "") {
              // Bos birakilmis birincil anahtar GONDERILMIYOR: modelden anahtarin
              // veritabani tarafindan uretilip uretilmedigini bilemiyoruz. Bos dize
              // gondermek, otomatik anahtarli bir tabloda anlasilmaz bir hatayla
              // duserdi; alani hic gondermemek veritabaninin yapilandirildigi seyi
              // yapmasina izin verir.
              if (column.isPrimaryKey) continue;
              values[column.name] = column.nullable ? null : "";
              continue;
            }

            values[column.name] = text;
          }

          return values;
        }

        function describe(error: unknown): string {
          return error instanceof Error ? error.message : String(error);
        }

        export async function createAction(
          tableName: string,
          _previous: FormState,
          form: FormData
        ): Promise<FormState> {
          const table = findTable(tableName);
          if (!table) return { error: `Unknown table: ${tableName}` };
          if (table.pattern === "readonly") {
            return { error: "This table has no primary key, so it cannot be edited." };
          }

          try {
            await createRow(table.name, readValues(table, form, { includePrimaryKey: true }));
          } catch (error) {
            return { error: describe(error) };
          }

          // redirect() bir istisna firlatarak calisir; try blogunun ICINDE cagrilsaydi
          // kendi catch'imiz onu bir hata sanip yonlendirmeyi yutardi.
          revalidatePath(`/${table.name}`);
          redirect(`/${table.name}`);
        }

        export async function updateAction(
          tableName: string,
          pkValue: string,
          _previous: FormState,
          form: FormData
        ): Promise<FormState> {
          const table = findTable(tableName);
          if (!table) return { error: `Unknown table: ${tableName}` };
          if (!table.primaryKey) {
            return { error: "This table has no single-column primary key, so it cannot be edited." };
          }

          try {
            await updateRow(
              table.name,
              table.primaryKey,
              pkValue,
              readValues(table, form, { includePrimaryKey: false })
            );
          } catch (error) {
            return { error: describe(error) };
          }

          revalidatePath(`/${table.name}`);
          redirect(`/${table.name}`);
        }

        export async function deleteAction(tableName: string, pkValue: string): Promise<FormState> {
          const table = findTable(tableName);
          if (!table) return { error: `Unknown table: ${tableName}` };
          if (!table.primaryKey) {
            return { error: "This table has no single-column primary key, so it cannot be edited." };
          }

          try {
            await deleteRow(table.name, table.primaryKey, pkValue);
          } catch (error) {
            return { error: describe(error) };
          }

          revalidatePath(`/${table.name}`);
          redirect(`/${table.name}`);
        }

        """;

    /// <summary>
    /// Form bileseni. Kolon -> widget esleme verisi lib/schema.ts'te; burada yalnizca
    /// o verinin nasil cizildigi var.
    /// </summary>
    private static string RowFormComponent() => """
        // Generated by Namines. Do not edit by hand.
        "use client";

        import type { CSSProperties } from "react";
        import { useActionState } from "react";
        import type { ConsoleColumn, ConsoleTable } from "../lib/schema";
        import type { FormState } from "../app/actions";

        const field: CSSProperties = {
          display: "block",
          width: "100%",
          padding: "6px 8px",
          fontSize: 14,
          fontFamily: "inherit",
          border: "1px solid #d1d5db",
          borderRadius: 6,
          boxSizing: "border-box",
        };

        export default function RowForm({
          table,
          action,
          initial,
          submitLabel,
        }: {
          table: ConsoleTable;
          action: (state: FormState, form: FormData) => Promise<FormState>;
          initial?: Record<string, unknown>;
          submitLabel: string;
        }) {
          const [state, formAction, pending] = useActionState(action, { error: null });

          // Yeni satırda, değerini veritabanının ürettiği kolon HİÇ sorulmuyor:
          // boş bir kutu göstermek, kullanıcıyı ya ezilecek ya reddedilecek bir
          // değer yazmaya davet eder. Var olan satırda gösteriliyor (salt-okunur),
          // çünkü hangi satırı düzenlediğini anahtarından anlarsın.
          const creating = initial === undefined;

          return (
            <form action={formAction} style={{ maxWidth: 520 }}>
              {state.error && (
                <pre
                  role="alert"
                  style={{
                    background: "#fef2f2",
                    border: "1px solid #fecaca",
                    color: "#7f1d1d",
                    padding: 12,
                    borderRadius: 6,
                    fontSize: 13,
                    whiteSpace: "pre-wrap",
                  }}
                >
                  {state.error}
                </pre>
              )}

              {table.columns
                .filter((column) => !(creating && column.isGenerated))
                .map((column) => (
                <div key={column.name} style={{ marginBottom: 14 }}>
                  <label
                    htmlFor={column.name}
                    style={{ display: "block", fontSize: 13, marginBottom: 4, color: "#374151" }}
                  >
                    {column.name}
                    {!column.nullable && !column.isPrimaryKey && (
                      <span style={{ color: "#b91c1c" }} aria-hidden="true">
                        {" *"}
                      </span>
                    )}
                    {column.isPrimaryKey && (
                      <span style={{ color: "#6b7280", fontSize: 12 }}> (key)</span>
                    )}
                  </label>
                  <Field
                    column={column}
                    initial={initial ? initial[column.name] : undefined}
                    readOnly={column.isPrimaryKey && initial !== undefined}
                  />
                </div>
              ))}

              <button
                type="submit"
                disabled={pending}
                style={{
                  padding: "8px 16px",
                  fontSize: 14,
                  borderRadius: 6,
                  border: "1px solid #111827",
                  background: pending ? "#6b7280" : "#111827",
                  color: "#ffffff",
                  cursor: pending ? "progress" : "pointer",
                }}
              >
                {pending ? "Saving..." : submitLabel}
              </button>
            </form>
          );
        }

        /**
         * On an existing row the key is shown but not editable: it is how the Gateway
         * finds the row being changed. Editing it here would describe two different
         * rows in one request.
         */
        function Field({
          column,
          initial,
          readOnly,
        }: {
          column: ConsoleColumn;
          initial: unknown;
          readOnly: boolean;
        }) {
          const value = initial === null || initial === undefined ? "" : String(initial);
          const style = readOnly ? { ...field, background: "#f3f4f6", color: "#6b7280" } : field;

          if (column.widget === "boolean") {
            // Uc secenek, checkbox degil: nullable bir boolean'da "bos" ile "false"
            // farkli seyler ve checkbox ikisini ayirt edemez.
            return (
              <select
                id={column.name}
                name={column.name}
                defaultValue={value}
                disabled={readOnly}
                style={style}
              >
                {column.nullable && <option value="">(null)</option>}
                <option value="true">true</option>
                <option value="false">false</option>
              </select>
            );
          }

          if (column.widget === "textarea") {
            return (
              <textarea
                id={column.name}
                name={column.name}
                defaultValue={value}
                readOnly={readOnly}
                rows={4}
                style={style}
              />
            );
          }

          return (
            <input
              id={column.name}
              name={column.name}
              defaultValue={value}
              readOnly={readOnly}
              type={column.widget}
              maxLength={column.maxLength ?? undefined}
              // required DEGIL: bos birakilan bir anahtar, veritabaninin anahtari
              // kendisinin uretmesi anlamina geliyor. Tarayicida zorunlu kilmak,
              // otomatik anahtarli tabloya satir eklemeyi imkansizlastirirdi.
              required={!column.nullable && !column.isPrimaryKey}
              style={style}
            />
          );
        }

        """;

    private static string DeleteButtonComponent() => """
        // Generated by Namines. Do not edit by hand.
        "use client";

        import { useState, useTransition } from "react";

        /**
         * Deleting asks first, and the question names the row.
         *
         * A one-click delete in a console that talks to a live database is a data-loss
         * default, and there is no undo behind it -- the Gateway runs a real DELETE.
         * The confirmation repeats the table and key so a mis-click on the wrong row
         * is visible before it happens, not after.
         */
        export default function DeleteButton({
          tableName,
          pkValue,
          action,
        }: {
          tableName: string;
          pkValue: string;
          action: () => Promise<{ error: string | null }>;
        }) {
          const [asking, setAsking] = useState(false);
          const [error, setError] = useState<string | null>(null);
          const [pending, startTransition] = useTransition();

          if (!asking) {
            return (
              <button
                type="button"
                onClick={() => setAsking(true)}
                style={{
                  padding: "8px 16px",
                  fontSize: 14,
                  borderRadius: 6,
                  border: "1px solid #b91c1c",
                  background: "transparent",
                  color: "#b91c1c",
                  cursor: "pointer",
                }}
              >
                Delete
              </button>
            );
          }

          return (
            <div style={{ fontSize: 13 }}>
              <p style={{ margin: "0 0 8px", color: "#7f1d1d" }}>
                Delete <strong>{pkValue}</strong> from <strong>{tableName}</strong>? This cannot be
                undone.
              </p>
              {error && (
                <pre style={{ color: "#7f1d1d", whiteSpace: "pre-wrap", fontSize: 13 }}>{error}</pre>
              )}
              <button
                type="button"
                disabled={pending}
                onClick={() =>
                  startTransition(async () => {
                    const result = await action();
                    // Silme basariliysa action yonlendirir ve buraya hic donulmez;
                    // buraya donmek, islemin BASARISIZ oldugu anlamina gelir.
                    if (result?.error) setError(result.error);
                  })
                }
                style={{
                  padding: "6px 12px",
                  fontSize: 13,
                  borderRadius: 6,
                  border: "1px solid #b91c1c",
                  background: "#b91c1c",
                  color: "#ffffff",
                  cursor: pending ? "progress" : "pointer",
                  marginRight: 8,
                }}
              >
                {pending ? "Deleting..." : "Yes, delete"}
              </button>
              <button
                type="button"
                onClick={() => setAsking(false)}
                style={{
                  padding: "6px 12px",
                  fontSize: 13,
                  borderRadius: 6,
                  border: "1px solid #d1d5db",
                  background: "transparent",
                  cursor: "pointer",
                }}
              >
                Cancel
              </button>
            </div>
          );
        }

        """;

    private static string NewRowPage() => """
        // Generated by Namines. Do not edit by hand.
        import Link from "next/link";
        import { notFound } from "next/navigation";
        import { findTable } from "../../../lib/schema";
        import { createAction } from "../../actions";
        import RowForm from "../../../components/RowForm";

        export default async function NewRowPage({ params }: { params: Promise<{ table: string }> }) {
          const { table: tableName } = await params;
          const table = findTable(tableName);
          if (!table) notFound();

          // Anahtarsiz tabloya yazmak Gateway tarafindan zaten reddedilir; formu hic
          // gostermemek, kullaniciyi dolduramayacagi bir formu doldurmaktan kurtarir.
          if (table.pattern === "readonly") {
            return (
              <div>
                <h1 style={{ fontSize: 20, marginTop: 0 }}>{table.name}</h1>
                <p style={{ fontSize: 13, color: "#6b7280" }}>
                  This table has no primary key, so rows cannot be added from the console.
                </p>
                <Link href={`/${table.name}`}>back</Link>
              </div>
            );
          }

          return (
            <div>
              <h1 style={{ fontSize: 20, marginTop: 0 }}>New row in {table.name}</h1>
              <RowForm
                table={table}
                action={createAction.bind(null, table.name)}
                submitLabel="Create"
              />
              <p style={{ marginTop: 16, fontSize: 13 }}>
                <Link href={`/${table.name}`}>back to {table.name}</Link>
              </p>
            </div>
          );
        }

        """;

    private static string EditRowPage() => """
        // Generated by Namines. Do not edit by hand.
        import Link from "next/link";
        import { notFound } from "next/navigation";
        import { findTable } from "../../../lib/schema";
        import { detailRow } from "../../../lib/gateway";
        import { deleteAction, updateAction } from "../../actions";
        import RowForm from "../../../components/RowForm";
        import DeleteButton from "../../../components/DeleteButton";

        export default async function EditRowPage({
          params,
        }: {
          params: Promise<{ table: string; id: string }>;
        }) {
          const { table: tableName, id } = await params;
          const table = findTable(tableName);
          if (!table) notFound();

          if (!table.primaryKey) {
            return (
              <div>
                <h1 style={{ fontSize: 20, marginTop: 0 }}>{table.name}</h1>
                <p style={{ fontSize: 13, color: "#6b7280" }}>
                  This table has no single-column primary key, so rows cannot be edited safely.
                </p>
                <Link href={`/${table.name}`}>back</Link>
              </div>
            );
          }

          const pkValue = decodeURIComponent(id);

          let row: Record<string, unknown> | null = null;
          let error: string | null = null;
          try {
            row = await detailRow<Record<string, unknown>>(table.name, table.primaryKey, pkValue);
          } catch (e) {
            error = e instanceof Error ? e.message : String(e);
          }

          if (error) {
            return (
              <div>
                <h1 style={{ fontSize: 20, marginTop: 0 }}>{table.name}</h1>
                <pre
                  style={{
                    background: "#fef2f2",
                    border: "1px solid #fecaca",
                    padding: 12,
                    borderRadius: 6,
                    fontSize: 13,
                    whiteSpace: "pre-wrap",
                  }}
                >
                  {error}
                </pre>
                <Link href={`/${table.name}`}>back</Link>
              </div>
            );
          }

          // Satir bulunamadiysa bos bir form gostermek, kullanicinin var olmayan bir
          // satiri duzenledigini sanmasina yol acardi.
          if (!row) notFound();

          return (
            <div>
              <h1 style={{ fontSize: 20, marginTop: 0 }}>
                {table.name}{" "}
                <span style={{ fontSize: 13, color: "#6b7280", fontWeight: 400 }}>{pkValue}</span>
              </h1>

              <RowForm
                table={table}
                action={updateAction.bind(null, table.name, pkValue)}
                initial={row}
                submitLabel="Save changes"
              />

              <div style={{ marginTop: 24, paddingTop: 16, borderTop: "1px solid #e5e7eb" }}>
                <DeleteButton
                  tableName={table.name}
                  pkValue={pkValue}
                  action={deleteAction.bind(null, table.name, pkValue)}
                />
              </div>

              <p style={{ marginTop: 16, fontSize: 13 }}>
                <Link href={`/${table.name}`}>back to {table.name}</Link>
              </p>
            </div>
          );
        }

        """;

    private static string TablePage() => """
        // Generated by Namines. Do not edit by hand.
        //
        // One dynamic page serves every table. Generating a file per table would
        // multiply the code you maintain by the number of tables without adding
        // anything — the shape differences live in lib/schema.ts as data.
        import Link from "next/link";
        import { notFound } from "next/navigation";
        import { findTable } from "../../lib/schema";
        import { listRows } from "../../lib/gateway";

        export default async function TablePage({
          params,
          searchParams,
        }: {
          params: Promise<{ table: string }>;
          searchParams: Promise<{ page?: string }>;
        }) {
          const { table: tableName } = await params;
          const { page: pageParam } = await searchParams;

          const table = findTable(tableName);
          if (!table) notFound();

          const page = Number(pageParam ?? "1") || 1;

          // Duzenleme yalnizca tek kolonluk bir anahtar varsa mumkun: Gateway satiri
          // anahtarla buluyor ve anahtarsiz bir UPDATE birden fazla satiri vurabilir.
          const editable = table.pattern !== "readonly" && table.primaryKey !== null;

          let rows: Record<string, unknown>[] = [];
          let total = 0;
          let error: string | null = null;

          try {
            // Sıralama kolonu olmadan sayfalar arası tutarlılık garanti değildir;
            // birincil anahtar varsa onu kullanıyoruz.
            const result = await listRows<Record<string, unknown>>(
              table.name,
              page,
              25,
              table.primaryKey
            );
            rows = result.rows;
            total = result.totalCount;
          } catch (e) {
            error = e instanceof Error ? e.message : String(e);
          }

          if (error) {
            return (
              <div>
                <h1 style={{ fontSize: 20, marginTop: 0 }}>{table.name}</h1>
                <pre
                  style={{
                    background: "#fef2f2",
                    border: "1px solid #fecaca",
                    padding: 12,
                    borderRadius: 6,
                    fontSize: 13,
                    whiteSpace: "pre-wrap",
                  }}
                >
                  {error}
                </pre>
              </div>
            );
          }

          return (
            <div>
              <h1 style={{ fontSize: 20, marginTop: 0 }}>
                {table.name}{" "}
                <span style={{ fontSize: 13, color: "#6b7280", fontWeight: 400 }}>
                  {total >= 0 ? `${total} rows` : ""}
                </span>
              </h1>

              {table.pattern === "readonly" ? (
                <p style={{ fontSize: 13, color: "#6b7280" }}>
                  This table has no primary key, so rows can be listed but not edited.
                </p>
              ) : (
                <p style={{ fontSize: 13, margin: "8px 0 16px" }}>
                  <Link href={`/${table.name}/new`}>+ New row</Link>
                </p>
              )}

              <div style={{ overflowX: "auto" }}>
                <table style={{ borderCollapse: "collapse", fontSize: 13, width: "100%" }}>
                  <thead>
                    <tr>
                      {table.columns.map((column) => (
                        <th
                          key={column.name}
                          style={{ textAlign: "left", padding: "6px 12px", whiteSpace: "nowrap" }}
                        >
                          {column.name}
                        </th>
                      ))}
                      {editable && <th style={{ padding: "6px 12px" }} />}
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((row, index) => (
                      <tr key={index} style={{ borderTop: "1px solid #e5e7eb" }}>
                        {table.columns.map((column) => (
                          <td key={column.name} style={{ padding: "6px 12px", whiteSpace: "nowrap" }}>
                            {format(row[column.name])}
                          </td>
                        ))}
                        {editable && (
                          <td style={{ padding: "6px 12px", whiteSpace: "nowrap" }}>
                            {/* Anahtar URL'e giriyor: kodlanmazsa "a/b" gibi bir anahtar
                                yolu ikiye boler ve yanlis sayfaya goturur. */}
                            <Link href={`/${table.name}/${encodeURIComponent(String(row[table.primaryKey as string]))}`}>
                              edit
                            </Link>
                          </td>
                        )}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {rows.length === 0 && (
                <p style={{ fontSize: 13, color: "#6b7280" }}>No rows on this page.</p>
              )}

              <nav style={{ marginTop: 16, fontSize: 13 }}>
                {page > 1 && <a href={`/${table.name}?page=${page - 1}`}>← previous</a>}{" "}
                {rows.length === 25 && <a href={`/${table.name}?page=${page + 1}`}>next →</a>}
              </nav>
            </div>
          );
        }

        /** null ile boş metni ayırt eder: ikisi de boş görünürse veri yanlış okunur. */
        function format(value: unknown) {
          if (value === null || value === undefined) {
            return <span style={{ color: "#9ca3af" }}>null</span>;
          }
          if (typeof value === "object") return JSON.stringify(value);
          return String(value);
        }

        """;
}
