using System.Collections.Generic;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>types.csharp</c> — 12 §P1. POCO record'lar.
///
/// <c>record</c> seçildi, <c>class</c> değil: bunlar veri taşıyıcı, kimlikleri
/// değerlerinden geliyor. Eşitlik karşılaştırması ve <c>with</c> ifadesi bedava
/// gelir; sınıf yazılsaydı her ikisi de elle yazılmayı beklerdi.
///
/// <see cref="EfCoreGenerator"/> ile karışmasın: orası EF'e bağlı entity'ler
/// üretiyor (DbContext, Fluent API). Bu hedef bağımlılıksız, yalnızca şeklin
/// kendisi — Gateway'den gelen JSON'u çözmek için.
/// </summary>
public sealed class CSharpTypesGenerator : IEjectGenerator
{
    public string Target => "types.csharp";
    public string DisplayName => "C# records";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings, supportsIndexes: false, supportsUniques: false);

        var files = new Dictionary<string, string>();

        foreach (var table in schema.Tables)
        {
            var name = EjectNaming.Pascal(table.Name);
            var sb = new StringBuilder();

            sb.AppendLine("// Generated by Namines. Do not edit by hand.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine();
            sb.AppendLine("namespace Namines.Generated;");
            sb.AppendLine();
            sb.AppendLine($"public sealed record {name}(");

            for (var i = 0; i < table.Columns.Count; i++)
            {
                var column = table.Columns[i];
                var comma = i == table.Columns.Count - 1 ? string.Empty : ",";
                var property = EjectNaming.Pascal(column.Name);

                // Kolon adı PascalCase'e çevrildiği için JSON eşlemesi ŞART:
                // olmadan "created_at" alanı sessizce null gelirdi.
                sb.AppendLine($"    [property: JsonPropertyName(\"{column.Name}\")] {CSharpType(column)} {property}{comma}");
            }

            sb.AppendLine(");");
            files[$"{name}.cs"] = sb.ToString();
        }

        return new EjectResult(files, warnings);
    }

    private static string CSharpType(SchemaColumn column)
    {
        var baseType = CanonicalType.Classify(column.Type) switch
        {
            TypeKind.Integer => "int",
            TypeKind.Long => "long",
            TypeKind.Decimal => "decimal",
            TypeKind.Double => "double",
            TypeKind.Boolean => "bool",
            TypeKind.Date or TypeKind.DateTime => "DateTime",
            TypeKind.Time => "TimeSpan",
            TypeKind.Uuid => "Guid",
            TypeKind.Json => "string",
            TypeKind.Binary => "byte[]",
            _ => "string",
        };

        // Değer tipleri için "?" nullable yapar; referans tipleri zaten nullable
        // olabilir ama nullable-reference-types açık projelerde işaret gerekir.
        return column.IsNullable ? baseType + "?" : baseType;
    }
}
