using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>orm.drizzle</c> — 12 §P1. TypeScript tarafında Prisma'nın eşi.
///
/// Prisma'dan farkı önemli: Drizzle şemayı KOD olarak tanımlar, ayrı bir dosya
/// biçimi ve üretici adımı yoktur. Bu yüzden çıktı doğrudan derlenebilir
/// TypeScript ve tipler şemadan çıkarılır — ayrı bir "generate" adımı gerekmez.
///
/// Motor seçimi Prisma'daki gibi provider dizesiyle değil, İTHAL EDİLEN MODÜLLE
/// yapılır (<c>pg-core</c> / <c>mysql-core</c> / <c>sqlite-core</c>). Yanlış modül
/// seçilirse dosya derlenmez — sessiz bir yanlış yapılandırma değil, derleme hatası.
/// </summary>
public sealed class DrizzleGenerator : IEjectGenerator
{
    public string Target => "orm.drizzle";
    public string DisplayName => "Drizzle ORM schema";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var dialect = Dialect(engine);
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Namines. Do not edit by hand.");

        var imports = new SortedSet<string>(StringComparer.Ordinal) { dialect.TableFn };
        foreach (var table in schema.Tables)
            foreach (var column in table.Columns)
                imports.Add(ColumnFn(column, dialect));

        sb.AppendLine($"import {{ {string.Join(", ", imports)} }} from \"drizzle-orm/{dialect.Module}\";");

        var hasRelations = EjectNaming.Relations(schema).Any();
        if (hasRelations) sb.AppendLine("import { relations } from \"drizzle-orm\";");
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            var variable = EjectNaming.Camel(table.Name);
            sb.AppendLine($"export const {variable} = {dialect.TableFn}(\"{table.Name}\", {{");

            foreach (var column in table.Columns)
                sb.AppendLine($"  {EjectNaming.Camel(column.Name)}: {ColumnExpression(column, table, dialect)},");

            sb.AppendLine("});");
            sb.AppendLine();
        }

        // İlişkiler ayrı bir blokta: Drizzle'da tablo tanımı ile ilişki tanımı
        // ayrıdır, çünkü ilişkiler karşılıklı referans içerir ve tek blokta
        // tanımlanırsa tanımlanmamış değişkene başvurulur.
        foreach (var group in EjectNaming.Relations(schema).GroupBy(r => r.From.Name))
        {
            var variable = EjectNaming.Camel(group.Key);
            sb.AppendLine($"export const {variable}Relations = relations({variable}, ({{ one }}) => ({{");
            foreach (var (from, fromColumn, to, toColumn, _) in group)
            {
                var field = EjectNaming.Camel(StripId(fromColumn.Name));
                sb.AppendLine(
                    $"  {field}: one({EjectNaming.Camel(to.Name)}, {{ " +
                    $"fields: [{variable}.{EjectNaming.Camel(fromColumn.Name)}], " +
                    $"references: [{EjectNaming.Camel(to.Name)}.{EjectNaming.Camel(toColumn.Name)}] }}),");
            }
            sb.AppendLine("}));");
            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["schema.ts"] = sb.ToString() },
            warnings);
    }

    private sealed record DrizzleDialect(string Module, string TableFn, string TextFn, string IntFn, string SerialFn);

    private static DrizzleDialect Dialect(DatabaseType engine) => engine switch
    {
        DatabaseType.PostgreSQL => new("pg-core", "pgTable", "text", "integer", "serial"),
        DatabaseType.MySQL or DatabaseType.MariaDB => new("mysql-core", "mysqlTable", "varchar", "int", "int"),
        DatabaseType.SQLite => new("sqlite-core", "sqliteTable", "text", "integer", "integer"),

        // Drizzle'ın SQL Server ve Oracle desteği yok. Sessizce pg-core yazmak
        // derlenebilir ama TAMAMEN yanlış bir dosya üretirdi.
        _ => throw new NotSupportedException(
            $"Drizzle does not support {engine}. Supported: PostgreSQL, MySQL, MariaDB, SQLite. " +
            "Use the Prisma or EF Core export for this engine."),
    };

    private static string ColumnFn(SchemaColumn column, DrizzleDialect dialect) =>
        CanonicalType.Classify(column.Type) switch
        {
            TypeKind.Integer => column.IsPK ? dialect.SerialFn : dialect.IntFn,
            TypeKind.Long => "bigint",
            TypeKind.Decimal => "decimal",
            TypeKind.Double => "doublePrecision",
            TypeKind.Boolean => "boolean",
            TypeKind.Date => "date",
            TypeKind.Time => "time",
            TypeKind.DateTime => "timestamp",
            TypeKind.Uuid => "uuid",
            TypeKind.Json => "json",
            _ => dialect.TextFn,
        };

    private static string ColumnExpression(SchemaColumn column, SchemaTable table, DrizzleDialect dialect)
    {
        var fn = ColumnFn(column, dialect);
        var args = $"\"{column.Name}\"";

        // Uzunluk yalnızca metin tiplerinde anlamlı; sayısal bir kolona uzunluk
        // vermek Drizzle'da derleme hatası.
        if (fn is "varchar" or "text" && column.Length is > 0)
            args += $", {{ length: {column.Length} }}";

        var sb = new StringBuilder($"{fn}({args})");

        if (column.IsPK && EjectNaming.PrimaryKeys(table).Count == 1)
            sb.Append(".primaryKey()");

        if (!column.IsNullable && !column.IsPK)
            sb.Append(".notNull()");

        return sb.ToString();
    }

    private static string StripId(string columnName)
    {
        foreach (var suffix in new[] { "_id", "Id", "_ID", "ID" })
            if (columnName.Length > suffix.Length && columnName.EndsWith(suffix, StringComparison.Ordinal))
                return columnName[..^suffix.Length];
        return columnName;
    }
}
