using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>orm.gorm</c> — 12 §P3. Go struct + tag.
///
/// Go'da alan adı büyük harfle başlamazsa DIŞA AÇIK olmaz; ne GORM ne de
/// <c>encoding/json</c> onu görebilir. Bu yüzden tüm alanlar PascalCase üretiliyor
/// ve gerçek kolon adı tag'de taşınıyor — küçük harfle başlayan bir alan sessizce
/// hiç doldurulmazdı.
///
/// Nullable kolonlar POINTER olarak üretiliyor: Go'da <c>string</c>'in sıfır değeri
/// <c>""</c>, <c>int</c>'inki <c>0</c>. Pointer olmadan "NULL" ile "boş metin" ya da
/// "sıfır" birbirinden ayırt edilemez.
/// </summary>
public sealed class GormGenerator : IEjectGenerator
{
    public string Target => "orm.gorm";
    public string DisplayName => "GORM structs";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Namines. Do not edit by hand.");
        sb.AppendLine("package models");
        sb.AppendLine();

        var needsTime = schema.Tables.SelectMany(t => t.Columns)
            .Any(c => CanonicalType.Classify(c.Type) is TypeKind.Date or TypeKind.Time or TypeKind.DateTime);
        if (needsTime)
        {
            sb.AppendLine("import \"time\"");
            sb.AppendLine();
        }

        foreach (var table in schema.Tables)
        {
            var structName = EjectNaming.Pascal(table.Name);
            sb.AppendLine($"type {structName} struct {{");

            foreach (var column in table.Columns)
            {
                var tags = new List<string> { $"column:{column.Name}" };
                if (column.IsPK) tags.Add("primaryKey");
                if (!column.IsNullable) tags.Add("not null");
                if (CanonicalType.Classify(column.Type) == TypeKind.Text && column.Length is > 0)
                    tags.Add($"size:{column.Length}");

                sb.AppendLine(
                    $"\t{EjectNaming.Pascal(column.Name)} {GoType(column)} " +
                    $"`gorm:\"{string.Join(";", tags)}\" json:\"{column.Name}\"`");
            }

            sb.AppendLine("}");
            sb.AppendLine();

            // GORM tablo adını çoğullar; gerçek adı bildirmeden yanlış tabloya gider.
            sb.AppendLine($"func ({structName}) TableName() string {{ return \"{table.Name}\" }}");
            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["models.go"] = sb.ToString() },
            warnings);
    }

    private static string GoType(SchemaColumn column)
    {
        var baseType = CanonicalType.Classify(column.Type) switch
        {
            TypeKind.Integer => "int",
            TypeKind.Long => "int64",
            TypeKind.Decimal or TypeKind.Double => "float64",
            TypeKind.Boolean => "bool",
            TypeKind.Date or TypeKind.Time or TypeKind.DateTime => "time.Time",
            TypeKind.Binary => "[]byte",
            _ => "string",
        };

        // []byte zaten nil olabilir; pointer yapmak gereksiz bir dolaylılık ekler.
        if (!column.IsNullable || baseType == "[]byte") return baseType;
        return "*" + baseType;
    }
}
