using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>contract.graphql</c> — 12 §P1. GraphQL şema tanımı (SDL).
///
/// Bu bir GraphQL SUNUCUSU değil, sözleşme: istemci tarafında kod üretmek ve
/// mevcut bir GraphQL ağ geçidine (Apollo Federation, Hasura remote schema)
/// bağlamak için. 08 §3'ün çalışan GraphQL endpoint'i ayrı ve büyük bir iş;
/// ikisini karıştırmamak için burada yalnızca SDL üretiliyor.
/// </summary>
public sealed class GraphqlSdlGenerator : IEjectGenerator
{
    public string Target => "contract.graphql";
    public string DisplayName => "GraphQL SDL";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings, supportsIndexes: false, supportsUniques: false);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Namines. Do not edit by hand.");
        sb.AppendLine();

        // GraphQL'de tarih/JSON yerleşik değil; custom scalar bildirmeden
        // kullanmak şemayı geçersiz kılar.
        var needsDateTime = schema.Tables.SelectMany(t => t.Columns)
            .Any(c => CanonicalType.Classify(c.Type) is TypeKind.Date or TypeKind.Time or TypeKind.DateTime);
        var needsJson = schema.Tables.SelectMany(t => t.Columns)
            .Any(c => CanonicalType.Classify(c.Type) is TypeKind.Json);

        if (needsDateTime) sb.AppendLine("scalar DateTime");
        if (needsJson) sb.AppendLine("scalar JSON");
        if (needsDateTime || needsJson) sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            var typeName = EjectNaming.Pascal(table.Name);
            sb.AppendLine($"type {typeName} {{");

            foreach (var column in table.Columns)
            {
                // GraphQL'de "!" ZORUNLU demek. PK her zaman zorunludur; nullable
                // kolonlarda işareti koymak, istemcinin null gelince patlamasına yol açar.
                var required = column.IsNullable && !column.IsPK ? string.Empty : "!";
                sb.AppendLine($"  {EjectNaming.Camel(column.Name)}: {GraphqlType(column)}{required}");
            }

            // İlişkiler alan olarak eklenir; yabancı anahtar nullable ise ilişki de
            // nullable olmalı, aksi hâlde yetim satırda şema ihlali doğar.
            foreach (var (_, fromColumn, to, _, _) in EjectNaming.Relations(schema).Where(r => r.From.Id == table.Id))
            {
                var field = EjectNaming.Camel(StripId(fromColumn.Name));
                var required = fromColumn.IsNullable ? string.Empty : "!";
                sb.AppendLine($"  {field}: {EjectNaming.Pascal(to.Name)}{required}");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("type Query {");
        foreach (var table in schema.Tables)
        {
            var typeName = EjectNaming.Pascal(table.Name);
            var pk = EjectNaming.PrimaryKey(table);

            sb.AppendLine($"  {EjectNaming.PluralCamel(table.Name)}(limit: Int, offset: Int): [{typeName}!]!");
            if (pk is not null)
                sb.AppendLine($"  {EjectNaming.Camel(table.Name)}ById({EjectNaming.Camel(pk.Name)}: {GraphqlType(pk)}!): {typeName}");
        }
        sb.AppendLine("}");

        return new EjectResult(
            new Dictionary<string, string> { ["schema.graphql"] = sb.ToString() },
            warnings);
    }

    private static string GraphqlType(SchemaColumn column) => CanonicalType.Classify(column.Type) switch
    {
        TypeKind.Integer => "Int",
        // GraphQL'in Int'i 32 bit; BIGINT'i Int yapmak büyük değerleri sessizce
        // taşırır. String olarak taşımak veriyi korur.
        TypeKind.Long => "String",
        TypeKind.Decimal or TypeKind.Double => "Float",
        TypeKind.Boolean => "Boolean",
        TypeKind.Date or TypeKind.Time or TypeKind.DateTime => "DateTime",
        TypeKind.Uuid => "ID",
        TypeKind.Json => "JSON",
        _ => "String",
    };

    private static string StripId(string columnName)
    {
        foreach (var suffix in new[] { "_id", "Id", "_ID", "ID" })
            if (columnName.Length > suffix.Length && columnName.EndsWith(suffix, System.StringComparison.Ordinal))
                return columnName[..^suffix.Length];
        return columnName;
    }
}
