using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>orm.typeorm</c> — 12 §P2. TypeORM entity dekoratörleri.
///
/// <c>name</c> her dekoratörde açıkça yazılıyor: TypeORM varsayılan olarak sınıf/
/// alan adını tablo/kolon adı sayar, yani PascalCase bir sınıf adı sessizce
/// yanlış tabloya bağlanır.
/// </summary>
public sealed class TypeOrmGenerator : IEjectGenerator
{
    public string Target => "orm.typeorm";
    public string DisplayName => "TypeORM entities";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var relationsByColumn = EjectNaming.Relations(schema).ToDictionary(r => r.FromColumn.Id, r => r);
        var files = new Dictionary<string, string>();

        foreach (var table in schema.Tables)
        {
            var className = EjectNaming.Pascal(table.Name);
            var sb = new StringBuilder();

            sb.AppendLine("// Generated by Namines. Do not edit by hand.");
            sb.AppendLine("import { Column, Entity, JoinColumn, ManyToOne, PrimaryColumn, PrimaryGeneratedColumn } from \"typeorm\";");

            foreach (var target in relationsByColumn.Values
                .Where(r => r.From.Id == table.Id)
                .Select(r => EjectNaming.Pascal(r.To.Name))
                .Distinct()
                .Where(n => n != className))
                sb.AppendLine($"import {{ {target} }} from \"./{target}\";");

            sb.AppendLine();
            sb.AppendLine($"@Entity({{ name: \"{table.Name}\" }})");
            sb.AppendLine($"export class {className} {{");

            var singlePk = EjectNaming.PrimaryKeys(table).Count == 1;

            foreach (var column in table.Columns)
            {
                var field = EjectNaming.Camel(column.Name);

                if (column.IsPK && singlePk)
                {
                    // Tamsayı PK'da otomatik artan; diğer tiplerde (UUID, metin)
                    // değeri uygulama üretir ve @PrimaryGeneratedColumn yanlış olur.
                    sb.AppendLine(CanonicalType.IsIntegral(CanonicalType.Classify(column.Type))
                        ? $"  @PrimaryGeneratedColumn({{ name: \"{column.Name}\" }})"
                        : $"  @PrimaryColumn({{ name: \"{column.Name}\" }})");
                    sb.AppendLine($"  {field}!: {TypeScriptTypesGenerator.TsType(column)};");
                    sb.AppendLine();
                    continue;
                }

                if (relationsByColumn.TryGetValue(column.Id, out var relation))
                {
                    var navigation = EjectNaming.Camel(StripId(column.Name));
                    sb.AppendLine($"  @ManyToOne(() => {EjectNaming.Pascal(relation.To.Name)})");
                    sb.AppendLine($"  @JoinColumn({{ name: \"{column.Name}\" }})");
                    sb.AppendLine($"  {navigation}!: {EjectNaming.Pascal(relation.To.Name)}{(column.IsNullable ? " | null" : string.Empty)};");
                    sb.AppendLine();
                    continue;
                }

                var options = new List<string> { $"name: \"{column.Name}\"" };
                if (column.IsNullable) options.Add("nullable: true");
                if (CanonicalType.Classify(column.Type) == TypeKind.Text && column.Length is > 0)
                    options.Add($"length: {column.Length}");

                sb.AppendLine($"  @Column({{ {string.Join(", ", options)} }})");
                sb.AppendLine($"  {field}{(column.IsNullable ? "?" : "!")}: {TypeScriptTypesGenerator.TsType(column)}{(column.IsNullable ? " | null" : string.Empty)};");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            files[$"{className}.ts"] = sb.ToString();
        }

        return new EjectResult(files, warnings);
    }

    private static string StripId(string columnName)
    {
        foreach (var suffix in new[] { "_id", "Id", "_ID", "ID" })
            if (columnName.Length > suffix.Length && columnName.EndsWith(suffix, StringComparison.Ordinal))
                return columnName[..^suffix.Length];
        return columnName;
    }
}

/// <summary>
/// <c>orm.sequelize</c> — 12 §P3. Sequelize model tanımları.
///
/// <c>freezeTableName</c> ve <c>timestamps: false</c> açıkça veriliyor: Sequelize
/// varsayılan olarak tablo adını çoğullar ve <c>createdAt</c>/<c>updatedAt</c>
/// kolonları OLDUĞUNU varsayar. İkisi de bizim şemamızda doğru değil ve
/// yazılmazsa model var olmayan kolonlara sorgu atar.
/// </summary>
public sealed class SequelizeGenerator : IEjectGenerator
{
    public string Target => "orm.sequelize";
    public string DisplayName => "Sequelize models";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Namines. Do not edit by hand.");
        sb.AppendLine("const { DataTypes } = require(\"sequelize\");");
        sb.AppendLine();
        sb.AppendLine("module.exports = (sequelize) => {");
        sb.AppendLine("  const models = {};");
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            var name = EjectNaming.Pascal(table.Name);
            sb.AppendLine($"  models.{name} = sequelize.define(\"{name}\", {{");

            foreach (var column in table.Columns)
            {
                var options = new List<string> { $"type: {SequelizeType(column)}", $"field: \"{column.Name}\"" };
                if (column.IsPK) options.Add("primaryKey: true");
                if (column.IsPK && CanonicalType.IsIntegral(CanonicalType.Classify(column.Type)))
                    options.Add("autoIncrement: true");
                options.Add($"allowNull: {(column.IsNullable ? "true" : "false")}");

                sb.AppendLine($"    {EjectNaming.Camel(column.Name)}: {{ {string.Join(", ", options)} }},");
            }

            sb.AppendLine($"  }}, {{ tableName: \"{table.Name}\", freezeTableName: true, timestamps: false }});");
            sb.AppendLine();
        }

        foreach (var (from, fromColumn, to, toColumn, _) in EjectNaming.Relations(schema))
        {
            sb.AppendLine(
                $"  models.{EjectNaming.Pascal(from.Name)}.belongsTo(models.{EjectNaming.Pascal(to.Name)}, " +
                $"{{ foreignKey: \"{EjectNaming.Camel(fromColumn.Name)}\", targetKey: \"{EjectNaming.Camel(toColumn.Name)}\" }});");
        }

        sb.AppendLine();
        sb.AppendLine("  return models;");
        sb.AppendLine("};");

        return new EjectResult(
            new Dictionary<string, string> { ["models.js"] = sb.ToString() },
            warnings);
    }

    private static string SequelizeType(SchemaColumn column) => CanonicalType.Classify(column.Type) switch
    {
        TypeKind.Integer => "DataTypes.INTEGER",
        TypeKind.Long => "DataTypes.BIGINT",
        TypeKind.Decimal => "DataTypes.DECIMAL",
        TypeKind.Double => "DataTypes.DOUBLE",
        TypeKind.Boolean => "DataTypes.BOOLEAN",
        TypeKind.Date => "DataTypes.DATEONLY",
        TypeKind.Time => "DataTypes.TIME",
        TypeKind.DateTime => "DataTypes.DATE",
        TypeKind.Uuid => "DataTypes.UUID",
        TypeKind.Json => "DataTypes.JSON",
        TypeKind.Binary => "DataTypes.BLOB",
        _ => column.Length is > 0 ? $"DataTypes.STRING({column.Length})" : "DataTypes.STRING",
    };
}
