using System;
using System.Collections.Generic;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;
using Namines.Infrastructure.Generators.DdlGenerator;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>mig.flyway</c> — 12 §P2. Flyway sürüm dosyası.
///
/// İçerik, mevcut ve gerçek motorlara karşı doğrulanmış DDL üreticisinden geliyor;
/// burada yalnızca Flyway'in beklediği DOSYA ADI kuralı uygulanıyor
/// (<c>V{n}__{ad}.sql</c>). DDL'i burada yeniden yazmak, golden-file testleriyle
/// korunan tek kaynağı ikiye bölerdi.
/// </summary>
public sealed class FlywayGenerator : IEjectGenerator
{
    private readonly IDdlGeneratorFactory _ddlFactory;

    public FlywayGenerator(IDdlGeneratorFactory ddlFactory) => _ddlFactory = ddlFactory;

    public string Target => "mig.flyway";
    public string DisplayName => "Flyway migration";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var ddl = _ddlFactory.GetGenerator(engine).Generate(schema);
        var name = Sanitize(schema.Name);

        return new EjectResult(
            new Dictionary<string, string>
            {
                // V1: bu ilk sürüm. Sonraki sürümleri Namines değil, kullanıcının
                // migration akışı üretir — numarayı burada tahmin etmek yanlış olurdu.
                [$"V1__{name}.sql"] = ddl,
            },
            new List<string>
            {
                "This is the initial migration (V1). Later versions must come from your own " +
                "migration flow; Namines cannot know what has already been applied.",
            });
    }

    internal static string Sanitize(string? value)
    {
        var cleaned = new string((value ?? "namines")
            .Select(c => char.IsLetterOrDigit(c) ? c : '_')
            .ToArray())
            .Trim('_');
        return cleaned.Length == 0 ? "namines" : cleaned.ToLowerInvariant();
    }
}

/// <summary>
/// <c>mig.liquibase</c> — 12 §P2. Liquibase changelog (XML).
///
/// <c>sql</c> etiketi kullanılıyor, Liquibase'in kendi <c>createTable</c>
/// etiketleri değil. Sebep: bizim DDL'imiz 6 motora karşı GERÇEK container'larda
/// doğrulandı; Liquibase'in soyut etiketlerine çevirmek, o doğrulamayı kaybedip
/// Liquibase'in kendi tip eşlemesine güvenmek olurdu. Motor bağımsızlığı zaten
/// bizim üreticimizde sağlanıyor.
/// </summary>
public sealed class LiquibaseGenerator : IEjectGenerator
{
    private readonly IDdlGeneratorFactory _ddlFactory;

    public LiquibaseGenerator(IDdlGeneratorFactory ddlFactory) => _ddlFactory = ddlFactory;

    public string Target => "mig.liquibase";
    public string DisplayName => "Liquibase changelog";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var ddl = _ddlFactory.GetGenerator(engine).Generate(schema);
        var id = FlywayGenerator.Sanitize(schema.Name);

        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.AppendLine("<!-- Generated by Namines. Do not edit by hand. -->");
        sb.AppendLine("<databaseChangeLog");
        sb.AppendLine("    xmlns=\"http://www.liquibase.org/xml/ns/dbchangelog\"");
        sb.AppendLine("    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
        sb.AppendLine("    xsi:schemaLocation=\"http://www.liquibase.org/xml/ns/dbchangelog");
        sb.AppendLine("        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd\">");
        sb.AppendLine();
        sb.AppendLine($"    <changeSet id=\"{id}-1\" author=\"namines\">");
        sb.AppendLine("        <sql splitStatements=\"true\" endDelimiter=\";\"><![CDATA[");
        // CDATA içinde "]]>" dizisi bölümü erkenden kapatır ve XML'i bozar.
        sb.AppendLine(ddl.Replace("]]>", "]]]]><![CDATA[>"));
        sb.AppendLine("        ]]></sql>");
        sb.AppendLine("    </changeSet>");
        sb.AppendLine();
        sb.AppendLine("</databaseChangeLog>");

        return new EjectResult(
            new Dictionary<string, string> { ["changelog.xml"] = sb.ToString() },
            new List<string>
            {
                "The changelog embeds raw DDL rather than Liquibase's abstract tags: the DDL is " +
                "verified against real database containers, and translating it would trade that " +
                "verification for Liquibase's own type mapping.",
            });
    }
}
