using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>types.python</c> — 12 §P2. Pydantic v2 modelleri.
///
/// v2 seçildi: v1 ile v2'nin API'leri uyumsuz (<c>Field</c> davranışı,
/// <c>model_config</c>) ve v1 artık bakım modunda. Hangi sürüm için üretildiği
/// dosyanın başında yazıyor, çünkü yanlış sürümde çalıştırılırsa hata mesajı
/// nedeni açıklamaz.
/// </summary>
public sealed class PydanticGenerator : IEjectGenerator
{
    public string Target => "types.python";
    public string DisplayName => "Pydantic v2 models";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings, supportsIndexes: false, supportsUniques: false);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Namines. Do not edit by hand.");
        sb.AppendLine("# Requires pydantic>=2.0");
        sb.AppendLine("from __future__ import annotations");
        sb.AppendLine();
        sb.AppendLine("from datetime import date, datetime, time");
        sb.AppendLine("from decimal import Decimal");
        sb.AppendLine("from typing import Any, Optional");
        sb.AppendLine("from uuid import UUID");
        sb.AppendLine();
        sb.AppendLine("from pydantic import BaseModel, Field");
        sb.AppendLine();
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            sb.AppendLine($"class {EjectNaming.Pascal(table.Name)}(BaseModel):");

            if (table.Columns.Count == 0)
            {
                // Python'da boş gövde sözdizimi hatası.
                sb.AppendLine("    pass");
                sb.AppendLine();
                continue;
            }

            foreach (var column in table.Columns)
            {
                var pythonName = EjectNaming.Snake(column.Name);
                var type = PythonType(column);

                // Kolon adı snake_case'e çevrildiği için alias ŞART: olmadan
                // "createdAt" alanı sessizce eşleşmez ve varsayılana düşer.
                var alias = pythonName == column.Name
                    ? string.Empty
                    : $" = Field(alias=\"{column.Name}\")";

                if (column.IsNullable)
                    sb.AppendLine(alias.Length == 0
                        ? $"    {pythonName}: Optional[{type}] = None"
                        : $"    {pythonName}: Optional[{type}]{alias}");
                else
                    sb.AppendLine($"    {pythonName}: {type}{alias}");
            }

            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["models.py"] = sb.ToString() },
            warnings);
    }

    internal static string PythonType(SchemaColumn column) => CanonicalType.Classify(column.Type) switch
    {
        TypeKind.Integer or TypeKind.Long => "int",
        TypeKind.Decimal => "Decimal",
        TypeKind.Double => "float",
        TypeKind.Boolean => "bool",
        TypeKind.Date => "date",
        TypeKind.Time => "time",
        TypeKind.DateTime => "datetime",
        TypeKind.Uuid => "UUID",
        TypeKind.Json => "Any",
        TypeKind.Binary => "bytes",
        _ => "str",
    };
}

/// <summary>
/// <c>orm.sqlalchemy</c> — 12 §P2. SQLAlchemy 2.0 declarative modeller.
///
/// 2.0 stili (<c>Mapped[...]</c> + <c>mapped_column</c>) seçildi: 1.x'in
/// <c>Column</c> stili hâlâ çalışıyor ama tip denetimi vermiyor. Üretilen kodun
/// değeri büyük ölçüde tip güvenliğinden geliyor.
/// </summary>
public sealed class SqlAlchemyGenerator : IEjectGenerator
{
    public string Target => "orm.sqlalchemy";
    public string DisplayName => "SQLAlchemy 2.0 models";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Namines. Do not edit by hand.");
        sb.AppendLine("# Requires SQLAlchemy>=2.0");
        sb.AppendLine("from __future__ import annotations");
        sb.AppendLine();
        sb.AppendLine("from datetime import date, datetime, time");
        sb.AppendLine("from decimal import Decimal");
        sb.AppendLine("from typing import Any, Optional");
        sb.AppendLine("from uuid import UUID");
        sb.AppendLine();
        sb.AppendLine("from sqlalchemy import ForeignKey, String");
        sb.AppendLine("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("class Base(DeclarativeBase):");
        sb.AppendLine("    pass");
        sb.AppendLine();
        sb.AppendLine();

        var relationsByColumn = EjectNaming.Relations(schema)
            .ToDictionary(r => r.FromColumn.Id, r => r);

        foreach (var table in schema.Tables)
        {
            sb.AppendLine($"class {EjectNaming.Pascal(table.Name)}(Base):");
            sb.AppendLine($"    __tablename__ = \"{table.Name}\"");
            sb.AppendLine();

            if (table.Columns.Count == 0)
            {
                sb.AppendLine("    pass");
                sb.AppendLine();
                continue;
            }

            foreach (var column in table.Columns)
            {
                var pythonName = EjectNaming.Snake(column.Name);
                var type = PydanticGenerator.PythonType(column);
                var annotation = column.IsNullable ? $"Optional[{type}]" : type;

                var args = new List<string>();
                if (pythonName != column.Name) args.Add($"\"{column.Name}\"");

                if (relationsByColumn.TryGetValue(column.Id, out var relation))
                    args.Add($"ForeignKey(\"{relation.To.Name}.{relation.ToColumn.Name}\")");

                // String uzunluğu yalnızca metin kolonlarında; sayısala vermek hata.
                if (CanonicalType.Classify(column.Type) == TypeKind.Text && column.Length is > 0)
                    args.Add($"String({column.Length})");

                if (column.IsPK) args.Add("primary_key=True");
                if (column.IsNullable) args.Add("nullable=True");

                sb.AppendLine($"    {pythonName}: Mapped[{annotation}] = mapped_column({string.Join(", ", args)})");
            }

            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["models.py"] = sb.ToString() },
            warnings);
    }
}

/// <summary>
/// <c>orm.django</c> — 12 §P2. Django modelleri.
///
/// <c>managed = False</c> YAZILMIYOR ve bu bilinçli: kullanıcı bu modelleri hem
/// mevcut bir veritabanına bağlamak hem de Django migration'larıyla yönetmek
/// isteyebilir. <c>db_table</c> ile gerçek tablo adı korunuyor, yani Django
/// tabloları yeniden adlandırmıyor.
/// </summary>
public sealed class DjangoGenerator : IEjectGenerator
{
    public string Target => "orm.django";
    public string DisplayName => "Django models";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        EjectNaming.CollectUnsupported(schema, warnings);

        var relationsByColumn = EjectNaming.Relations(schema)
            .ToDictionary(r => r.FromColumn.Id, r => r);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Namines. Do not edit by hand.");
        sb.AppendLine("from django.db import models");
        sb.AppendLine();
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            sb.AppendLine($"class {EjectNaming.Pascal(table.Name)}(models.Model):");

            var wroteField = false;
            foreach (var column in table.Columns)
            {
                // Django birincil anahtarı kendi yönetir; tamsayı PK'yı ayrıca
                // yazmak "id" ile çakışır.
                if (column.IsPK && CanonicalType.IsIntegral(CanonicalType.Classify(column.Type)))
                {
                    sb.AppendLine($"    {EjectNaming.Snake(column.Name)} = models.AutoField(primary_key=True, db_column=\"{column.Name}\")");
                    wroteField = true;
                    continue;
                }

                if (relationsByColumn.TryGetValue(column.Id, out var relation))
                {
                    var onDelete = relation.Relation.OnDelete switch
                    {
                        ReferentialAction.Cascade => "models.CASCADE",
                        ReferentialAction.SetNull => "models.SET_NULL",
                        ReferentialAction.SetDefault => "models.SET_DEFAULT",
                        // Django'da NO ACTION karşılığı DO_NOTHING; PROTECT daha
                        // katı olurdu ve veritabanındaki davranıştan saparak
                        // uygulamada beklenmedik hatalar üretirdi.
                        _ => "models.DO_NOTHING",
                    };

                    var nullArg = column.IsNullable ? ", null=True" : string.Empty;
                    sb.AppendLine(
                        $"    {EjectNaming.Snake(StripId(column.Name))} = models.ForeignKey(" +
                        $"\"{EjectNaming.Pascal(relation.To.Name)}\", on_delete={onDelete}, " +
                        $"db_column=\"{column.Name}\"{nullArg})");
                    wroteField = true;
                    continue;
                }

                sb.AppendLine($"    {EjectNaming.Snake(column.Name)} = {DjangoField(column)}");
                wroteField = true;
            }

            if (!wroteField) sb.AppendLine("    pass");

            sb.AppendLine();
            sb.AppendLine("    class Meta:");
            sb.AppendLine($"        db_table = \"{table.Name}\"");
            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["models.py"] = sb.ToString() },
            warnings);
    }

    private static string DjangoField(SchemaColumn column)
    {
        var args = new List<string> { $"db_column=\"{column.Name}\"" };
        if (column.IsNullable) { args.Add("null=True"); args.Add("blank=True"); }

        var field = CanonicalType.Classify(column.Type) switch
        {
            TypeKind.Integer => "models.IntegerField",
            TypeKind.Long => "models.BigIntegerField",
            TypeKind.Decimal => "models.DecimalField",
            TypeKind.Double => "models.FloatField",
            TypeKind.Boolean => "models.BooleanField",
            TypeKind.Date => "models.DateField",
            TypeKind.Time => "models.TimeField",
            TypeKind.DateTime => "models.DateTimeField",
            TypeKind.Uuid => "models.UUIDField",
            TypeKind.Json => "models.JSONField",
            TypeKind.Binary => "models.BinaryField",
            _ => "models.CharField",
        };

        // DecimalField Django'da max_digits/decimal_places ZORUNLU tutar;
        // vermeden model doğrulaması hata verir.
        if (field == "models.DecimalField") { args.Add("max_digits=18"); args.Add("decimal_places=2"); }
        if (field == "models.CharField") args.Add($"max_length={column.Length ?? 255}");

        return $"{field}({string.Join(", ", args)})";
    }

    private static string StripId(string columnName)
    {
        foreach (var suffix in new[] { "_id", "Id", "_ID", "ID" })
            if (columnName.Length > suffix.Length && columnName.EndsWith(suffix, System.StringComparison.Ordinal))
                return columnName[..^suffix.Length];
        return columnName;
    }
}
