using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>sdk.typescript</c> — 12 §7 / §P0. Gateway için tip güvenli istemci.
///
/// <see cref="TypeScriptTypesGenerator"/> yalnızca satır ŞEKİLLERİNİ veriyordu;
/// müşteri hâlâ elle <c>fetch</c> yazıp gövdeyi doğru kurmak zorundaydı. Bu hedef
/// o boşluğu kapatıyor: <c>client.users.list()</c> çağrısı doğru tabloyu, doğru
/// gövdeyi ve doğru dönüş tipini birlikte getiriyor.
///
/// <b>Tablo başına metot üretiliyor</b>, tek bir <c>list(table)</c> değil. Sebep:
/// jenerik bir imzada tablo adını yanlış yazmak çalışma zamanına kalır; üretilen
/// metotta yanlış ad DERLEME hatasıdır. SDK'nın tüm değeri hatayı erkene çekmek.
///
/// <b>Anahtar tarayıcıya konmuyor.</b> Üretilen istemci anahtarı yapılandırmadan
/// alıyor ve README bunu sunucu tarafında kullanmayı söylüyor; tarayıcıdan doğrudan
/// çağrılırsa anahtar herkese açılır ve Gateway'in tablo izinleri o anahtarın
/// yetkisi kadar geniş olur.
/// </summary>
public sealed class TypeScriptSdkGenerator : IEjectGenerator
{
    public string Target => "sdk.typescript";
    public string DisplayName => "TypeScript SDK (Gateway client)";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();

        var keyless = schema.Tables.Where(t => EjectNaming.PrimaryKeys(t).Count != 1).ToList();
        foreach (var table in keyless)
            warnings.Add(
                $"{table.Name}: no single-column primary key, so get/update/delete are not " +
                "generated for it. The Gateway refuses keyed writes without one; only list " +
                "and export are available.");

        var files = new Dictionary<string, string>
        {
            ["types.ts"] = new TypeScriptTypesGenerator().Generate(schema, engine).Files["types.ts"],
            ["client.ts"] = Client(schema, engine),
            ["index.ts"] = "export * from \"./types\";\nexport * from \"./client\";\n",
            ["README.md"] = Readme(schema),
        };

        return new EjectResult(files, warnings);
    }

    private static string Client(DatabaseSchema schema, DatabaseType engine)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Namines. Do not edit by hand.");
        sb.AppendLine("import type { Database } from \"./types\";");
        sb.AppendLine();
        sb.Append(Runtime(engine));
        sb.AppendLine();

        sb.AppendLine("export class NaminesClient {");
        sb.AppendLine("  private readonly options: NaminesClientOptions;");
        sb.AppendLine();
        sb.AppendLine("  constructor(options: NaminesClientOptions) {");
        sb.AppendLine("    if (!options.apiKey) {");
        sb.AppendLine("      throw new Error(\"apiKey is required.\");");
        sb.AppendLine("    }");
        sb.AppendLine("    if (!options.connectionString) {");
        sb.AppendLine("      throw new Error(");
        sb.AppendLine("        \"connectionString is required: the Gateway needs it to reach your database.\"");
        sb.AppendLine("      );");
        sb.AppendLine("    }");
        sb.AppendLine("    this.options = options;");
        sb.AppendLine("  }");
        sb.AppendLine();
        sb.Append(RequestMethods());
        sb.AppendLine();

        foreach (var table in schema.Tables)
            sb.Append(TableAccessor(table));

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Ortak istek gövdesi. Her tablo metodunun kendi fetch'ini yazması, bağlantı
    /// dizesi ya da başlık eklemeyi bir yerde unutmak demekti.
    /// </summary>
    private static string RequestMethods() => """
        private body(payload: Record<string, unknown>) {
          return {
            ...payload,
            connectionString: this.options.connectionString,
            dbType: this.options.dbType ?? DEFAULT_DB_TYPE,
          };
        }

        private url(path: string) {
          const base = (this.options.baseUrl ?? "").replace(/\/$/, "");
          return `${base}/api/gateway/${path}`;
        }

        private headers() {
          return {
            "Content-Type": "application/json",
            "X-Namines-Key": this.options.apiKey,
          };
        }

        private async send(path: string, payload: Record<string, unknown>) {
          const doFetch = this.options.fetch ?? fetch;
          const response = await doFetch(this.url(path), {
            method: "POST",
            headers: this.headers(),
            body: JSON.stringify(this.body(payload)),
          });

          if (!response.ok) {
            throw new NaminesError(response.status, await response.text());
          }
          return response;
        }

        private async request<T>(path: string, payload: Record<string, unknown>): Promise<T> {
          const response = await this.send(path, payload);
          // 204 gövdesiz döner; json() çağırmak ayrıştırma hatası verir.
          if (response.status === 204) return null as T;
          return (await response.json()) as T;
        }

        /** Dışa aktarım CSV ya da JSON METNİ döndürür, ayrıştırılmış nesne değil. */
        private async requestText(path: string, payload: Record<string, unknown>): Promise<string> {
          const response = await this.send(path, payload);
          return await response.text();
        }
      """;

    private static string TableAccessor(SchemaTable table)
    {
        var property = TypeScriptTypesGenerator.PropertyName(table.Name);
        var rowType = $"Database[{Literal(table.Name)}]";
        var primaryKeys = EjectNaming.PrimaryKeys(table);
        var pk = primaryKeys.Count == 1 ? primaryKeys[0] : null;

        var sb = new StringBuilder();
        sb.AppendLine($"  readonly {property} = {{");
        sb.AppendLine($"    list: (options?: ListOptions<{rowType}>) =>");
        sb.AppendLine($"      this.request<ListResult<{rowType}>>(\"list\", {{");
        sb.AppendLine($"        tableName: {Literal(table.Name)},");
        sb.AppendLine("        page: options?.page ?? 1,");
        sb.AppendLine("        pageSize: options?.pageSize ?? 25,");
        sb.AppendLine($"        orderByColumn: options?.orderBy ?? {(pk is null ? "undefined" : Literal(pk.Name))},");
        sb.AppendLine("        sortDirection: options?.direction ?? \"Asc\",");
        sb.AppendLine("        filters: options?.filters,");
        sb.AppendLine("        select: options?.select,");
        sb.AppendLine("        expand: options?.expand,");
        sb.AppendLine("      }),");
        sb.AppendLine();
        sb.AppendLine($"    export: (options?: ExportOptions<{rowType}>) =>");
        sb.AppendLine("      this.requestText(\"export\", {");
        sb.AppendLine($"        tableName: {Literal(table.Name)},");
        sb.AppendLine("        format: options?.format ?? \"csv\",");
        sb.AppendLine("        maxRows: options?.maxRows ?? 10000,");
        sb.AppendLine($"        orderByColumn: options?.orderBy ?? {(pk is null ? "undefined" : Literal(pk.Name))},");
        sb.AppendLine("        filters: options?.filters,");
        sb.AppendLine("        select: options?.select,");
        sb.AppendLine("      }),");

        if (pk is not null)
        {
            // Anahtarı olmayan tabloya get/update/delete üretilmiyor: Gateway
            // anahtarsız yazmayı zaten reddediyor, metot üretmek çağıranı
            // çalışma zamanında patlayacak bir yola sokardı.
            sb.AppendLine();
            sb.AppendLine($"    get: (key: string | number) =>");
            sb.AppendLine($"      this.request<{rowType} | null>(\"detail\", {{");
            sb.AppendLine($"        tableName: {Literal(table.Name)},");
            sb.AppendLine($"        pkColumn: {Literal(pk.Name)},");
            sb.AppendLine("        pkValue: String(key),");
            sb.AppendLine("      }),");
            sb.AppendLine();
            sb.AppendLine($"    create: (values: Partial<Record<keyof {rowType}, string | null>>) =>");
            sb.AppendLine("      this.request<WriteResult>(\"create\", {");
            sb.AppendLine($"        tableName: {Literal(table.Name)},");
            sb.AppendLine("        values,");
            sb.AppendLine("      }),");
            sb.AppendLine();
            sb.AppendLine($"    update: (key: string | number, values: Partial<Record<keyof {rowType}, string | null>>) =>");
            sb.AppendLine("      this.request<WriteResult>(\"update\", {");
            sb.AppendLine($"        tableName: {Literal(table.Name)},");
            sb.AppendLine($"        pkColumn: {Literal(pk.Name)},");
            sb.AppendLine("        pkValue: String(key),");
            sb.AppendLine("        values,");
            sb.AppendLine("      }),");
            sb.AppendLine();
            sb.AppendLine("    delete: (key: string | number) =>");
            sb.AppendLine("      this.request<WriteResult>(\"delete\", {");
            sb.AppendLine($"        tableName: {Literal(table.Name)},");
            sb.AppendLine($"        pkColumn: {Literal(pk.Name)},");
            sb.AppendLine("        pkValue: String(key),");
            sb.AppendLine("      }),");
        }

        sb.AppendLine("  };");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string Runtime(DatabaseType engine) => $$"""
        export interface NaminesClientOptions {
          /** Gateway base URL, e.g. https://api.example.com */
          baseUrl?: string;
          /** Gateway API key. Keep it on the server; see README. */
          apiKey: string;
          /** Connection string the Gateway uses to reach your database. */
          connectionString: string;
          /** Defaults to the engine this SDK was generated for. */
          dbType?: string;
          fetch?: typeof fetch;
        }

        export type FilterOperator =
          | "Eq" | "Neq" | "Gt" | "Gte" | "Lt" | "Lte"
          | "Like" | "In" | "IsNull" | "IsNotNull";

        export interface Filter<TRow> {
          column: keyof TRow & string;
          operator: FilterOperator;
          values: (string | null)[];
        }

        export interface Expand {
          fromColumn: string;
          table: string;
          toColumn: string;
          as?: string;
        }

        export interface ListOptions<TRow> {
          page?: number;
          pageSize?: number;
          orderBy?: keyof TRow & string;
          direction?: "Asc" | "Desc";
          filters?: Filter<TRow>[];
          select?: (keyof TRow & string)[];
          expand?: Expand[];
        }

        export interface ExportOptions<TRow> {
          format?: "csv" | "json";
          maxRows?: number;
          orderBy?: keyof TRow & string;
          filters?: Filter<TRow>[];
          select?: (keyof TRow & string)[];
        }

        export interface ListResult<TRow> {
          rows: TRow[];
          page: number;
          pageSize: number;
          /** -1 when the caller asked to skip the count. */
          totalCount: number;
        }

        export interface WriteResult {
          affectedRows: number;
          /** Populated only where the engine can return it in one statement. */
          row: Record<string, unknown> | null;
        }

        /**
         * Thrown for any non-2xx response. The Gateway explains refusals precisely
         * (table permission, rate limit, origin, or a write that would have touched
         * more than one row) and that message is far more useful than a generic
         * failure — so it is carried through verbatim.
         */
        export class NaminesError extends Error {
          constructor(readonly status: number, message: string) {
            super(message);
            this.name = "NaminesError";
          }
        }

        const DEFAULT_DB_TYPE = "{{engine}}";
        """;

    private static string Readme(DatabaseSchema schema)
    {
        var first = schema.Tables.FirstOrDefault();
        var example = first is null
            ? "client"
            : $"client.{TypeScriptTypesGenerator.PropertyName(first.Name)}";

        return $$"""
        # {{schema.Name}} — Namines SDK

        Type-safe client for the Namines Gateway, generated from your schema.

        ```ts
        import { NaminesClient } from "./sdk";

        const client = new NaminesClient({
          baseUrl: process.env.NAMINES_API_URL,
          apiKey: process.env.NAMINES_API_KEY!,
          connectionString: process.env.NAMINES_DB_CONNECTION!,
        });

        const page = await {{example}}.list({ pageSize: 50 });
        ```

        ## Keep the key on the server

        The API key is a bearer credential: anyone holding it can reach every table
        the key is permitted to read. Calling this SDK **from the browser** ships the
        key to every visitor. Use it from a server route, an edge function, or a
        backend service — never from client-side code.

        ## What the types buy you

        Table and column names are checked at compile time. A typo in a column name
        inside `select` or `filters` is a build error, not a runtime surprise — that
        is the whole point of generating a client instead of writing `fetch` calls.

        ## Errors

        Every non-2xx response throws `NaminesError` with the Gateway's own message:
        which table was refused, which limit was hit, or why a write was rolled back.

        """;
    }

    private static string Literal(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";
}
