using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>types.typescript</c> — 12 §P0. Gateway SDK'sının tip tabanı.
///
/// Üretilen <c>Database</c> haritası bilinçli: tablo adından satır tipine gitmeyi
/// sağlıyor, böylece SDK <c>list&lt;"users"&gt;()</c> gibi bir imzayla doğru satır
/// tipini döndürebiliyor. Yalnızca ayrı ayrı <c>interface</c>'ler üretilseydi,
/// çağıran her yerde tipi elle yazmak zorunda kalırdı.
/// </summary>
public sealed class TypeScriptTypesGenerator : IEjectGenerator
{
    public string Target => "types.typescript";
    public string DisplayName => "TypeScript types";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        // TypeScript tipleri kısıt taşımaz: CHECK/index/unique burada ifade edilemez.
        EjectNaming.CollectUnsupported(schema, warnings, supportsIndexes: false, supportsUniques: false);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Namines. Do not edit by hand.");
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            var name = EjectNaming.Pascal(table.Name);
            sb.AppendLine($"export interface {name} {{");
            foreach (var column in table.Columns)
            {
                var optional = column.IsNullable ? " | null" : string.Empty;
                sb.AppendLine($"  {PropertyName(column.Name)}: {TsType(column)}{optional};");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("export interface Database {");
        foreach (var table in schema.Tables)
            sb.AppendLine($"  {PropertyName(table.Name)}: {EjectNaming.Pascal(table.Name)};");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export type TableName = keyof Database;");

        return new EjectResult(
            new Dictionary<string, string> { ["types.ts"] = sb.ToString() },
            warnings);
    }

    /// <summary>
    /// Tanımlayıcı olarak geçerli olmayan adlar tırnaklanır. Aksi hâlde
    /// <c>order-id</c> gibi bir kolon üretilen dosyayı ayrıştırılamaz kılardı.
    /// </summary>
    internal static string PropertyName(string name) =>
        name.Length > 0 && (char.IsLetter(name[0]) || name[0] == '_') &&
        name.All(c => char.IsLetterOrDigit(c) || c == '_')
            ? name
            : $"\"{name.Replace("\"", "\\\"")}\"";

    internal static string TsType(SchemaColumn column) => CanonicalType.Classify(column.Type) switch
    {
        TypeKind.Integer or TypeKind.Double or TypeKind.Decimal => "number",
        // BIGINT number'a sığmayabilir (2^53 üstü sessizce yuvarlanır); string
        // olarak taşımak veriyi korur.
        TypeKind.Long => "string",
        TypeKind.Boolean => "boolean",
        // Tarihler JSON üzerinden string gelir; Date demek, JSON.parse sonrası
        // gerçekte string olan bir değeri Date sanmak olurdu.
        TypeKind.Date or TypeKind.Time or TypeKind.DateTime => "string",
        TypeKind.Uuid => "string",
        TypeKind.Json => "unknown",
        TypeKind.Binary => "string",
        _ => "string",
    };
}
