using System.Collections.Generic;
using System.Text;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;

namespace Namines.Infrastructure.Generators.Eject;

/// <summary>
/// <c>types.zod</c> — 12 §P1. Form doğrulaması için çalışma zamanı şemaları.
///
/// TypeScript tiplerinden farkı: bunlar derleme zamanında değil, ÇALIŞMA
/// zamanında doğruluyor. O yüzden uzunluk gibi veritabanı kısıtları buraya
/// taşınabiliyor — TypeScript'te <c>varchar(255)</c>'i ifade etmenin yolu yok,
/// Zod'da <c>.max(255)</c> var. Kullanıcı 300 karakter yazdığında hatayı
/// veritabanından değil formdan alır.
/// </summary>
public sealed class ZodSchemaGenerator : IEjectGenerator
{
    public string Target => "types.zod";
    public string DisplayName => "Zod schemas";

    public EjectResult Generate(DatabaseSchema schema, DatabaseType engine)
    {
        var warnings = new List<string>();
        // Zod uzunluk taşıyabiliyor ama CHECK ifadelerini ve index'leri taşıyamaz.
        EjectNaming.CollectUnsupported(schema, warnings, supportsIndexes: false, supportsUniques: false);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Namines. Do not edit by hand.");
        sb.AppendLine("import { z } from \"zod\";");
        sb.AppendLine();

        foreach (var table in schema.Tables)
        {
            var name = EjectNaming.Pascal(table.Name);
            sb.AppendLine($"export const {name}Schema = z.object({{");
            foreach (var column in table.Columns)
                sb.AppendLine($"  {TypeScriptTypesGenerator.PropertyName(column.Name)}: {ZodType(column)},");
            sb.AppendLine("});");
            // Tipi şemadan türetmek, ikisinin ayrışmasını imkânsız kılar.
            sb.AppendLine($"export type {name} = z.infer<typeof {name}Schema>;");
            sb.AppendLine();
        }

        return new EjectResult(
            new Dictionary<string, string> { ["schemas.ts"] = sb.ToString() },
            warnings);
    }

    private static string ZodType(SchemaColumn column)
    {
        var kind = CanonicalType.Classify(column.Type);

        var expression = kind switch
        {
            TypeKind.Integer => "z.number().int()",
            TypeKind.Long => "z.string()",
            TypeKind.Decimal or TypeKind.Double => "z.number()",
            TypeKind.Boolean => "z.boolean()",
            TypeKind.Uuid => "z.string().uuid()",
            TypeKind.Date or TypeKind.Time or TypeKind.DateTime => "z.string().datetime()",
            TypeKind.Json => "z.unknown()",
            TypeKind.Binary => "z.string()",
            _ => column.Length is > 0 ? $"z.string().max({column.Length})" : "z.string()",
        };

        // .nullable() ile .optional() farklı: nullable "değer null olabilir",
        // optional "alan hiç bulunmayabilir". Veritabanı kolonu NULL kabul ediyorsa
        // doğru olan nullable — alan her zaman var, değeri yok olabilir.
        return column.IsNullable ? expression + ".nullable()" : expression;
    }
}
