/**
 * Namines Desk — şemadan arayüze DETERMİNİSTİK çeviri.
 *
 * <b>Buranın tamamı saf fonksiyon ve AI YOKTUR.</b> Ürünün vaadi bu: aynı
 * veritabanı her zaman aynı arayüzü üretir. Bir alanın metin mi sayı mı onay
 * kutusu mu olacağı tahmin edilmiyor, `dbintrospect`'in döndürdüğü kolon
 * meta verisinden ÇIKARILIYOR.
 */

export interface ColumnRef {
  table: string;
  column: string;
}

export interface DeskColumn {
  name: string;
  type: string;
  length: number | null;
  isPK: boolean;
  isFK: boolean;
  isNullable: boolean;
  references: ColumnRef | null;
}

export interface DeskTable {
  name: string;
  canWrite: boolean;
  columns: DeskColumn[];
}

/** Formda kullanılacak giriş bileşeni. */
export type FieldKind = 'text' | 'textarea' | 'number' | 'boolean' | 'date' | 'datetime' | 'reference';

/**
 * Kolon tipinden giriş bileşenine eşleme.
 *
 * Motorlar aynı şeyi farklı adlandırıyor (`int4`/`INT`/`NUMBER`), o yüzden
 * eşleme tam ad değil ÖN EK/İÇERİK üzerinden. Tanınmayan tip `text`'e düşer —
 * yanlış bir bileşen göstermektense en genel olanı göstermek daha güvenli.
 */
export function fieldKind(column: DeskColumn): FieldKind {
  // FK önce gelir: tipi ne olursa olsun, hedefi olan bir alan seçim alanıdır.
  if (column.references) return 'reference';

  const t = column.type.toLowerCase();

  if (/(^|\b)(bool|boolean|bit)/.test(t)) return 'boolean';
  if (/(timestamp|datetime)/.test(t)) return 'datetime';
  if (/(^|\b)date/.test(t)) return 'date';
  if (/(int|serial|numeric|decimal|float|double|real|money)/.test(t)) return 'number';
  // Uzunluğu olmayan ya da çok uzun metin → çok satırlı.
  if (/(text|json|xml|clob)/.test(t)) return 'textarea';
  if (column.length !== null && column.length > 255) return 'textarea';

  return 'text';
}

/**
 * Bir satırı tek satırda özetleyen kolon — liste ve FK açılır listelerinde
 * "42" yerine "Ayşe Demir" göstermek için.
 *
 * Sıra bilinçli: insan tarafından okunabilir bir ad alanı varsa o, yoksa ilk
 * metin alanı, o da yoksa birincil anahtar. Hiçbir tahmin yürütmüyor —
 * yalnızca var olan kolon adlarına bakıyor.
 */
export function displayColumn(table: DeskTable): string {
  const preferred = ['name', 'title', 'full_name', 'fullname', 'label', 'email', 'username', 'plate'];
  for (const candidate of preferred) {
    const hit = table.columns.find(c => c.name.toLowerCase() === candidate);
    if (hit) return hit.name;
  }
  const firstText = table.columns.find(c => !c.isPK && fieldKind(c) === 'text');
  if (firstText) return firstText.name;
  return primaryKey(table) ?? table.columns[0]?.name ?? '';
}

/**
 * Güncelleme/silme için anahtar kolon.
 *
 * <b>Bileşik anahtar DESTEKLENMİYOR ve bu bilinçli:</b> Gateway'in
 * `update`/`delete` uçları tek bir `pkColumn`/`pkValue` alıyor. Bileşik
 * anahtarlı bir tabloyu düzenlenebilir göstermek, kaydetme anında sessizce
 * YANLIŞ SATIRI güncellemek demek olurdu. Böyle tablolar salt-okunur gösterilir
 * (bkz. `isEditable`).
 */
export function primaryKey(table: DeskTable): string | null {
  const pks = table.columns.filter(c => c.isPK);
  return pks.length === 1 ? pks[0].name : null;
}

/** Tablo düzenlenebilir mi: yazma izni + tek kolonlu birincil anahtar. */
export function isEditable(table: DeskTable): boolean {
  return table.canWrite && primaryKey(table) !== null;
}

/**
 * Ekleme formunda gösterilecek kolonlar.
 *
 * Otomatik artan birincil anahtar dışarıda: kullanıcıya "id gir" demek hem
 * gereksiz hem de çakışma üretir. Tespit tip üzerinden (`serial`/`identity`)
 * ya da PK+sayısal olmasından — motorlar identity bilgisini farklı taşıyor.
 */
export function insertableColumns(table: DeskTable): DeskColumn[] {
  return table.columns.filter(c => {
    if (!c.isPK) return true;
    const t = c.type.toLowerCase();
    const autoGenerated = /serial|identity/.test(t) || /(int|bigint|smallint)/.test(t);
    return !autoGenerated;
  });
}

/** Düzenleme formunda gösterilecek kolonlar — anahtar hariç (değiştirilemez). */
export function editableColumns(table: DeskTable): DeskColumn[] {
  const pk = primaryKey(table);
  return table.columns.filter(c => c.name !== pk);
}

/**
 * Boş bir metin kutusunu ne olarak göndermeli.
 *
 * <b>NULL ile boş metin AYNI ŞEY DEĞİL.</b> Nullable bir alanda boş bırakmak
 * "değer yok" demektir; NOT NULL bir alanda ise boş metnin kendisi geçerli bir
 * değerdir. İkisini karıştırmak, veritabanına sessizce yanlış veri yazar.
 */
export function normalizeValue(column: DeskColumn, raw: string): string | null {
  if (raw === '' && column.isNullable) return null;
  return raw;
}

/** Hücreyi listede gösterilecek metne çevirir. */
export function formatCell(value: unknown): string {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'boolean') return value ? '✓' : '✗';
  return String(value);
}
