CREATE TABLE "events" (
    "id" NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" VARCHAR2(120) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "last_seen_at" TIMESTAMP NULL,
    CONSTRAINT "PK_events" PRIMARY KEY ("id")
);

