CREATE TABLE [Users] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Email] NVARCHAR(255) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
    , CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id])
);

CREATE TABLE [Products] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(200) NOT NULL,
    [Price] DECIMAL NOT NULL,
    [Stock] INT NOT NULL DEFAULT 0
    , CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([Id])
);

CREATE TABLE [Orders] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [UserId] INT NOT NULL,
    [Total] DECIMAL NOT NULL,
    [PlacedAt] DATETIME2 NOT NULL
    , CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id])
);

CREATE TABLE [OrderItems] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [OrderId] INT NOT NULL,
    [ProductId] INT NOT NULL,
    [Quantity] INT NOT NULL DEFAULT 1
    , CONSTRAINT [PK_OrderItems] PRIMARY KEY CLUSTERED ([Id])
);

ALTER TABLE [Orders] WITH CHECK ADD CONSTRAINT [FK_Orders_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [Users] ([Id])
ON DELETE CASCADE;

ALTER TABLE [OrderItems] WITH CHECK ADD CONSTRAINT [FK_OrderItems_Orders_OrderId] FOREIGN KEY([OrderId])
REFERENCES [Orders] ([Id])
ON DELETE CASCADE;

ALTER TABLE [OrderItems] WITH CHECK ADD CONSTRAINT [FK_OrderItems_Products_ProductId] FOREIGN KEY([ProductId])
REFERENCES [Products] ([Id])
ON DELETE CASCADE;

