CREATE TABLE [Users] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Email] NVARCHAR(255) NOT NULL
    , CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id])
);

CREATE TABLE [Addresses] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [UserId] INT NOT NULL,
    [Line1] NVARCHAR(200) NOT NULL
    , CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED ([Id])
);

CREATE TABLE [Orders] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [UserId] INT NOT NULL,
    [AddressId] INT NOT NULL
    , CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id])
);

ALTER TABLE [Addresses] WITH CHECK ADD CONSTRAINT [FK_Addresses_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [Users] ([Id]);

ALTER TABLE [Orders] WITH CHECK ADD CONSTRAINT [FK_Orders_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [Users] ([Id]);

ALTER TABLE [Orders] WITH CHECK ADD CONSTRAINT [FK_Orders_Addresses_AddressId] FOREIGN KEY([AddressId])
REFERENCES [Addresses] ([Id]);

