using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Namines.Core.Enums;
using Namines.Core.Interfaces;
using Namines.Core.Models;
using Namines.Core.Prompts;
using Namines.Infrastructure.AI;

namespace Namines.Infrastructure.Services;

public class SmartSeedService : ISmartSeedService
{
    private readonly GroqAIService _groqService;

    public SmartSeedService(GroqAIService groqService)
    {
        _groqService = groqService;
    }

    public async Task<SmartSeedResult> GenerateSmartSeedAsync(DatabaseSchema schema, DatabaseType dbType, string? domainHint, int rowCount = 50)
    {
        if (schema?.Tables == null || schema.Tables.Count == 0)
        {
            return new SmartSeedResult
            {
                SqlScript = "-- Hata: Veri üretilecek tablo bulunamadı.",
                DetectedDomain = "Bilinmiyor"
            };
        }

        // 1. Domain/Sektör Tespiti
        string domain = string.IsNullOrWhiteSpace(domainHint) 
            ? DomainKeywords.DetectDomain(schema) 
            : domainHint;

        // 2. FK İlişkilerine Göre Topolojik Sıralama (Parent Önce, Child Sonra)
        var sortedTableNames = SortTablesTopologically(schema);

        // 3. AI veya Programmatik SQL Seed Script Üretimi
        string sqlScript;
        try
        {
            sqlScript = await _groqService.GenerateSmartSeedSqlAsync(schema, dbType, domain, rowCount);
        }
        catch (Exception ex)
        {
            // AI Limiti veya hata durumlarında programatik veri üretim motoruna güvenli geri dönüş yap
            Console.WriteLine($"[SmartSeed Warning] AI seed generation failed ({ex.Message}). Falling back to robust C# programmatic engine.");
            sqlScript = GenerateMockDataProgrammatically(schema, dbType, rowCount);
        }

        // 4. İstatistiklerin Hesaplanması
        var rowCounts = new Dictionary<string, int>();
        foreach (var tableName in sortedTableNames)
        {
            rowCounts[tableName] = rowCount;
        }

        long estimatedSizeBytes = Encoding.UTF8.GetByteCount(sqlScript);

        return new SmartSeedResult
        {
            SqlScript = sqlScript,
            DetectedDomain = domain,
            TableRowCounts = rowCounts,
            EstimatedSizeBytes = estimatedSizeBytes
        };
    }

    private string GenerateMockDataProgrammatically(DatabaseSchema schema, DatabaseType dbType, int rowCount)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Programmatic Mock Data generated by Namines fallback seeding engine");
        sb.AppendLine();

        var sortedTableNames = SortTablesTopologically(schema);

        foreach (var tableName in sortedTableNames)
        {
            var table = schema.Tables.FirstOrDefault(t => string.Equals(t.Name, tableName, StringComparison.OrdinalIgnoreCase));
            if (table == null) continue;

            sb.AppendLine($"-- Table: {table.Name}");

            // Generate realistic mock records
            int rowsToGenerate = Math.Min(rowCount, 10); // 10 is ideal for quick SQLite playground checks
            for (int i = 1; i <= rowsToGenerate; i++)
            {
                var columns = new List<string>();
                var values = new List<string>();

                foreach (var col in table.Columns)
                {
                    // Primary key integer logic
                    if (col.IsPK && (col.Type.Contains("INT", StringComparison.OrdinalIgnoreCase) || col.Type.Contains("LONG", StringComparison.OrdinalIgnoreCase)))
                    {
                        columns.Add(col.Name);
                        values.Add(i.ToString());
                        continue;
                    }

                    columns.Add(col.Name);

                    // Foreign key reference logic (point to i index)
                    if (col.IsFK)
                    {
                        int fkValue = ((i - 1) % rowsToGenerate) + 1;
                        values.Add(fkValue.ToString());
                    }
                    else
                    {
                        // Generate mock values based on field names and types
                        string typeUpper = col.Type.ToUpper();
                        string colLower = col.Name.ToLower();

                        if (typeUpper.Contains("CHAR") || typeUpper.Contains("TEXT") || typeUpper.Contains("STRING"))
                        {
                            if (colLower.Contains("surname") || colLower.Contains("lastname"))
                            {
                                string[] surnames = { "Yilmaz", "Kaya", "Demir", "Celik", "Sahin", "Yildiz", "Ozturk", "Kilic", "Arslan" };
                                values.Add($"'{surnames[i % surnames.Length]}'");
                            }
                            else if (colLower.Contains("name") || colLower.Contains("first"))
                            {
                                string[] names = { "Ahmet", "Mehmet", "Ayse", "Fatma", "Ali", "Can", "Zeynep", "Elif", "Mustafa", "Emre" };
                                values.Add($"'{names[i % names.Length]}'");
                            }
                            else if (colLower.Contains("email") || colLower.Contains("mail"))
                            {
                                values.Add($"'user{i}@namines.com'");
                            }
                            else if (colLower.Contains("phone") || colLower.Contains("tel"))
                            {
                                values.Add($"'+9055512345{i}'");
                            }
                            else
                            {
                                values.Add($"'{table.Name}_{col.Name}_{i}'");
                            }
                        }
                        else if (typeUpper.Contains("INT") || typeUpper.Contains("DECIMAL") || typeUpper.Contains("FLOAT") || typeUpper.Contains("NUMERIC") || typeUpper.Contains("DOUBLE") || typeUpper.Contains("REAL"))
                        {
                            values.Add((i * 10).ToString());
                        }
                        else if (typeUpper.Contains("DATE") || typeUpper.Contains("TIME"))
                        {
                            values.Add("'2026-05-31 20:00:00'");
                        }
                        else if (typeUpper.Contains("BIT") || typeUpper.Contains("BOOL"))
                        {
                            values.Add((i % 2 == 0) ? "1" : "0");
                        }
                        else
                        {
                            values.Add($"'{col.Name}_{i}'");
                        }
                    }
                }

                var columnsEscaped = columns.Select(c => $"\"{c}\"");
                sb.AppendLine($"INSERT INTO \"{table.Name}\" ({string.Join(", ", columnsEscaped)}) VALUES ({string.Join(", ", values)});");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private List<string> SortTablesTopologically(DatabaseSchema schema)
    {
        var sorted = new List<string>();
        var visited = new HashSet<string>();

        void Visit(string tableName)
        {
            if (visited.Contains(tableName)) return;
            visited.Add(tableName);

            var table = schema.Tables.FirstOrDefault(t => string.Equals(t.Name, tableName, StringComparison.OrdinalIgnoreCase));
            if (table == null) return;

            // Bu tablonun bağımlı olduğu parent tabloları bul (Source = Child, Target = Parent)
            var parentTableIds = schema.Relations
                .Where(r => r.SourceTableId == table.Id)
                .Select(r => r.TargetTableId)
                .Distinct();

            foreach (var parentId in parentTableIds)
            {
                var parentTable = schema.Tables.FirstOrDefault(t => t.Id == parentId);
                if (parentTable != null && !string.Equals(parentTable.Name, tableName, StringComparison.OrdinalIgnoreCase))
                {
                    Visit(parentTable.Name);
                }
            }

            sorted.Add(tableName);
        }

        foreach (var table in schema.Tables)
        {
            Visit(table.Name);
        }

        return sorted;
    }
}
