'use client';

import { useState } from 'react';
import Link from 'next/link';
import {
  FileCode2,
  Cpu,
  Box,
  Share2,
  Play,
  Users2,
  GitCompare,
  LayoutTemplate,
  ArrowRight,
  Check,
  Copy,
  Terminal,
  X,
  Sparkles
} from 'lucide-react';

interface BuilderFeature {
  id: string;
  icon: typeof FileCode2;
  tag: string;
  badge?: string;
  title: string;
  description: string;
  directHref?: string;
  modalTitle: string;
  modalSubtitle: string;
  codeSnippetTitle: string;
  codeLanguage: string;
  codeSnippet: string;
  actionLabel: string;
  actionHref: string;
}

const BUILDER_FEATURES: BuilderFeature[] = [
  {
    id: 'ir',
    icon: FileCode2,
    tag: 'FOUNDATION',
    badge: 'JSON AST',
    title: 'Canonical Schema IR',
    description:
      'Engine-agnostic intermediate representation (ir.json). Version, branch, and inspect schema changes programmatically with absolute AST precision.',
    modalTitle: 'Canonical Schema IR (ir.json)',
    modalSubtitle: 'Deterministic AST data structure decoupling your database schema from ORM syntax.',
    codeSnippetTitle: 'schema.ir.json',
    codeLanguage: 'json',
    codeSnippet: `{
  "$schema": "https://namines.dev/schemas/ir-v1.json",
  "name": "ecommerce_core",
  "version": "1.4.0",
  "tables": [
    {
      "name": "orders",
      "columns": [
        { "name": "id", "type": "bigint", "primaryKey": true },
        { "name": "user_id", "type": "uuid", "foreignKey": "users.id", "onDelete": "Cascade" },
        { "name": "total", "type": "decimal(12,2)", "nullable": false }
      ],
      "indexes": [{ "columns": ["user_id"], "type": "btree" }]
    }
  ]
}`,
    actionLabel: 'Inspect in Demo Blueprints',
    actionHref: '/demo',
  },
  {
    id: 'mcp',
    icon: Cpu,
    tag: 'DEV TOOLS',
    badge: 'Claude & Cursor',
    title: 'MCP Server & CLI',
    description:
      'Native Model Context Protocol integration for Claude, Cursor, and terminal agents. Architect schemas and inspect live drift directly from your AI agent.',
    modalTitle: 'Namines Model Context Protocol (MCP)',
    modalSubtitle: 'Connect Claude Desktop, Cursor, or Cline directly to your database lifecycle.',
    codeSnippetTitle: 'claude_desktop_config.json',
    codeLanguage: 'json',
    codeSnippet: `{
  "mcpServers": {
    "namines": {
      "command": "npx",
      "args": ["-y", "@namines/mcp-server@latest"],
      "env": {
        "NAMINES_PROJECT_ID": "prj_live_94821"
      }
    }
  }
}`,
    actionLabel: 'Start Project CLI',
    actionHref: '/new',
  },
  {
    id: 'sandboxes',
    icon: Box,
    tag: 'TESTING',
    badge: 'Docker Engine',
    title: 'Ephemeral Sandboxes',
    description:
      'Docker-backed ephemeral verification. Run raw DDL against genuine database containers before touching staging or production clusters.',
    modalTitle: 'Ephemeral Container Sandboxes',
    modalSubtitle: 'Disposable Docker containers spun up in 180ms to test migration rollback and lock contention.',
    codeSnippetTitle: 'ephemeral-verify.log',
    codeLanguage: 'bash',
    codeSnippet: `$ namines sandbox verify --engine postgres:17
[docker] Spawning isolated container id=namines-sb-819a (142ms)
[docker] Applying baseline schema (14 tables)... OK
[verify] Executing proposed DDL: ALTER TABLE orders ADD COLUMN idempotency_key VARCHAR;
[verify] Testing zero-downtime lock contention... PASSED (0.00s lock timeout)
[verify] Applying automated rollback script... REVERTED CLEANLY
[docker] Sandbox destroyed. All 24 safety constraints passed.`,
    actionLabel: 'Test in Workbench',
    actionHref: '/demo',
  },
  {
    id: 'eject',
    icon: Share2,
    tag: 'ZERO LOCK-IN',
    badge: '19 Dialects',
    title: '19 Eject Targets',
    description:
      'Export instantly to Prisma, EF Core, Drizzle, TypeORM, Kysely, raw SQL dialects, or fully working TypeScript SDKs with complete type safety.',
    modalTitle: 'Zero Lock-in Eject Targets',
    modalSubtitle: 'Generate production-ready code for any modern stack in milliseconds.',
    codeSnippetTitle: 'schema.prisma',
    codeLanguage: 'prisma',
    codeSnippet: `// Auto-generated by Namines CLI
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(uuid())
  email     String   @unique
  orders    Order[]
  createdAt DateTime @default(now()) @map("created_at")
}

model Order {
  id        BigInt   @id @default(autoincrement())
  userId    String   @map("user_id")
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  total     Decimal  @db.Decimal(12, 2)
}`,
    actionLabel: 'Explore Eject in Blueprints',
    actionHref: '/demo',
  },
  {
    id: 'wasm',
    icon: Play,
    tag: 'PLAYGROUND',
    badge: 'In-Browser SQL',
    title: 'WASM SQLite Console',
    description:
      'Zero-latency browser engine. Test table relationships, write queries, and preview realistic mock datasets without launching a server.',
    modalTitle: 'WebAssembly SQLite Studio',
    modalSubtitle: 'Instant in-memory relational engine running directly in your browser tab.',
    codeSnippetTitle: 'playground-query.sql',
    codeLanguage: 'sql',
    codeSnippet: `-- Instant local WASM query
SELECT
  o.id AS order_id,
  u.email AS customer_email,
  o.total,
  COUNT(oi.id) AS item_count
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN order_items oi ON oi.order_id = o.id
GROUP BY o.id, u.email, o.total
ORDER BY o.total DESC
LIMIT 5;`,
    actionLabel: 'Launch Interactive Studio',
    actionHref: '/demo',
  },
  {
    id: 'multiplayer',
    icon: Users2,
    tag: 'COLLABORATION',
    badge: 'Live Presence',
    title: 'Real-Time Multiplayer Canvas',
    description:
      'Infinite ERD workspace with presence indicators, shared branch rooms, and live cursor tracking powered by a SignalR Redis backplane.',
    modalTitle: 'Multiplayer Real-Time Canvas',
    modalSubtitle: 'Collaborate live on relational database architectures with your entire engineering team.',
    codeSnippetTitle: 'signalr-canvas-session.ts',
    codeLanguage: 'typescript',
    codeSnippet: `import { CanvasHubClient } from '@namines/client';

// Join server-authoritative branch room
const session = await CanvasHubClient.connect({
  branchId: 'br_feature_multi_currency',
  user: { name: 'Sarah Chen', role: 'Staff Architect' },
  onPresenceUpdate: (peers) => console.log(\`\${peers.length} architects collaborating live\`),
  onSchemaChange: (delta) => renderERDDelta(delta),
});`,
    actionLabel: 'Open Multiplayer Canvas',
    actionHref: '/canvas',
  },
  {
    id: 'review',
    icon: GitCompare,
    tag: 'GOVERNANCE',
    badge: 'Live Route',
    title: 'Change Review UI (/review)',
    description:
      'Visual migration diffs, automated risk scoring (Safe, Warning, Destructive), and affected code path scanning before any PR merges.',
    modalTitle: 'Database Change Review Portal',
    modalSubtitle: 'Inspect migration AST diffs, automated risk classifications, and affected code paths.',
    codeSnippetTitle: 'migration-analysis.diff',
    codeLanguage: 'diff',
    codeSnippet: `[RISK LEVEL: SAFE] Auto-approval eligible (Project Opt-in)
+ CREATE TABLE "wallets" (
+   "id" BIGSERIAL PRIMARY KEY,
+   "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
+   "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
+   "balance" NUMERIC(14,2) NOT NULL DEFAULT 0.00
+ );
+ CREATE INDEX CONCURRENTLY "idx_wallets_user" ON "wallets"("user_id");

// Zero locks acquired. Safe for zero-downtime execution.`,
    actionLabel: 'Go to /review Portal',
    actionHref: '/review',
  },
  {
    id: 'desk',
    icon: LayoutTemplate,
    tag: 'ADMIN PANEL',
    badge: 'Auto Next.js',
    title: 'Namines Desk',
    description:
      'Auto-generated Next.js management portal with row-level CRUD, read-only SQL console, audit logs, and fine-grained API key permissions.',
    modalTitle: 'Namines Desk (CRUD Management Portal)',
    modalSubtitle: 'Instant administrative backoffice generated directly from your database AST.',
    codeSnippetTitle: 'desk-config.ts',
    codeLanguage: 'typescript',
    codeSnippet: `import { createDeskPortal } from '@namines/desk';

export default createDeskPortal({
  schema: './namines/ir.json',
  auth: { provider: 'session-cookie', roles: ['admin', 'ops'] },
  features: {
    liveCrud: true,
    auditLog: true,
    readOnlySqlConsole: true,
  },
});`,
    actionLabel: 'Explore Admin Schemas',
    actionHref: '/demo',
  },
];

export default function BuilderGrid() {
  const [activeFeature, setActiveFeature] = useState<BuilderFeature | null>(null);
  const [copiedCode, setCopiedCode] = useState(false);

  const handleCopyCode = () => {
    if (!activeFeature) return;
    navigator.clipboard.writeText(activeFeature.codeSnippet);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <section id="builder-grid" className="relative z-10 w-full max-w-[var(--w-app)] mx-auto px-4 sm:px-6 lg:px-8 py-20 sm:py-28 border-t border-surface-500/80">
      {/* Section Header */}
      <div className="text-center mb-16 max-w-2xl mx-auto">
        <span className="font-mono text-xs font-bold tracking-widest uppercase text-accent-text block mb-3">
          Builder Ecosystem
        </span>
        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-content-primary mb-4">
          Intuitive infrastructure, designed for builders
        </h2>
        <p className="text-xs sm:text-sm text-content-muted leading-relaxed">
          Everything your engineering team needs to design, verify, branch, and monitor relational database architectures with zero operational guesswork. Click any card to inspect code, tooling, and live integrations.
        </p>
      </div>

      {/* 8-Grid Cards (All 100% Clickable & Interactive) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        {BUILDER_FEATURES.map((feat) => {
          const Icon = feat.icon;
          return (
            <div
              key={feat.id}
              onClick={() => setActiveFeature(feat)}
              className="group rounded-[var(--radius-card)] border border-surface-500 bg-surface-900/85 hover:bg-surface-800 p-6 flex flex-col justify-between transition-all duration-300 shadow-lg hover:border-accent hover:shadow-xl hover:scale-[1.02] cursor-pointer"
            >
              <div>
                {/* Card Header: Icon, Tag & Interactive Badge */}
                <div className="flex items-center justify-between mb-4">
                  <div className="w-10 h-10 rounded-[var(--radius-control)] bg-surface-800 group-hover:bg-accent/20 flex items-center justify-center border border-surface-500 group-hover:border-accent transition-colors shadow-sm">
                    <Icon className="w-4 h-4 text-accent-text group-hover:text-accent transition-colors" />
                  </div>
                  <div className="flex items-center gap-1.5">
                    {feat.badge && (
                      <span className="text-[10px] font-mono px-1.5 py-0.5 rounded-[var(--radius-control)] bg-surface-750 text-content-secondary group-hover:bg-accent/15 group-hover:text-accent-text transition-colors">
                        {feat.badge}
                      </span>
                    )}
                    <span className="text-[10px] font-mono tracking-wider uppercase text-content-subtle group-hover:text-content-muted transition-colors">
                      {feat.tag}
                    </span>
                  </div>
                </div>

                {/* Title & Description */}
                <h3 className="text-base font-bold text-content-primary mb-2 group-hover:text-accent-text transition-colors flex items-center gap-1.5">
                  <span>{feat.title}</span>
                </h3>
                <p className="text-xs text-content-muted leading-relaxed">
                  {feat.description}
                </p>
              </div>

              {/* Bottom Interactive Trigger Button */}
              <div className="mt-5 pt-3 border-t border-surface-500/60 flex items-center justify-between text-xs font-mono text-content-subtle group-hover:text-accent-text transition-colors">
                <span className="font-semibold">Explore details</span>
                <div className="flex items-center gap-1">
                  <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Quick Interactive CLI / Playground Bar */}
      <div className="mt-12 rounded-[var(--radius-modal)] border border-surface-500 bg-surface-800/80 p-5 sm:p-6 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-xl">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-[var(--radius-control)] bg-surface-700 flex items-center justify-center border border-surface-500">
            <Cpu className="w-4 h-4 text-accent-text" />
          </div>
          <div className="flex flex-col">
            <span className="text-xs font-bold text-content-primary">
              Ready to automate your schema migrations?
            </span>
            <span className="text-[11px] text-content-muted font-mono">
              Try the CLI or connect via MCP to your local Claude / Cursor instance.
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <div className="px-3.5 py-2 rounded-[var(--radius-control)] bg-surface-900 border border-surface-500 font-mono text-xs text-content-primary select-all">
            npx namines@latest init
          </div>
          <Link
            href="/demo"
            className="px-4 py-2 rounded-[var(--radius-control)] bg-accent hover:bg-accent-hover text-accent-on font-bold text-xs uppercase tracking-wider transition-colors shrink-0 cursor-pointer"
          >
            Launch Playground
          </Link>
        </div>
      </div>

      {/* ── Feature Deep-Dive Interactive Modal ── */}
      {activeFeature && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-3 sm:p-6 backdrop-blur-sm"
          onClick={() => setActiveFeature(null)}
        >
          <div
            className="relative w-full max-w-3xl overflow-hidden rounded-[var(--radius-modal)] border border-surface-600 bg-surface-900 shadow-2xl flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-surface-600 bg-surface-850 p-5 sm:p-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-[var(--radius-control)] bg-accent/20 border border-accent flex items-center justify-center text-accent">
                  <activeFeature.icon className="w-5 h-5" />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-accent-text">
                      {activeFeature.tag}
                    </span>
                    {activeFeature.badge && (
                      <span className="font-mono text-[10px] px-1.5 py-0.2 rounded-[var(--radius-control)] bg-white/[0.08] text-content-secondary">
                        {activeFeature.badge}
                      </span>
                    )}
                  </div>
                  <h3 className="text-lg font-bold text-content-primary">
                    {activeFeature.modalTitle}
                  </h3>
                </div>
              </div>

              <button
                type="button"
                onClick={() => setActiveFeature(null)}
                className="rounded-[var(--radius-control)] p-1.5 text-content-muted hover:bg-surface-700 hover:text-content-primary transition-colors cursor-pointer"
                title="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="p-5 sm:p-6 space-y-4">
              <p className="text-xs sm:text-sm text-content-secondary leading-relaxed">
                {activeFeature.modalSubtitle}
              </p>

              {/* Code Snippet Box with Copy Button */}
              <div className="rounded-[var(--radius-card)] border border-surface-600 bg-surface-950 overflow-hidden">
                <div className="flex items-center justify-between px-4 py-2 border-b border-surface-700 bg-surface-850">
                  <div className="flex items-center gap-2">
                    <Terminal className="w-3.5 h-3.5 text-accent-text" />
                    <span className="font-mono text-xs text-content-primary font-semibold">
                      {activeFeature.codeSnippetTitle}
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={handleCopyCode}
                    className="flex items-center gap-1.5 text-xs font-mono text-content-muted hover:text-content-primary transition-colors cursor-pointer"
                  >
                    {copiedCode ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-success-text" />
                        <span className="text-success-text font-semibold">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy snippet</span>
                      </>
                    )}
                  </button>
                </div>
                <pre className="p-4 font-mono text-xs text-content-primary overflow-x-auto leading-relaxed max-h-72">
                  {activeFeature.codeSnippet}
                </pre>
              </div>
            </div>

            {/* Modal Footer Actions */}
            <div className="flex items-center justify-between border-t border-surface-600 bg-surface-850 p-4 sm:p-5">
              <div className="flex items-center gap-1.5 text-xs font-mono text-content-subtle">
                <Sparkles className="w-3.5 h-3.5 text-accent" />
                <span>Deterministic Zero Drift Guaranteed</span>
              </div>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setActiveFeature(null)}
                  className="px-4 py-2 rounded-[var(--radius-control)] bg-surface-700 hover:bg-surface-600 text-content-secondary text-xs font-bold transition-colors cursor-pointer"
                >
                  Close
                </button>
                <Link
                  href={activeFeature.actionHref}
                  className="inline-flex items-center gap-2 px-5 py-2 rounded-[var(--radius-control)] bg-accent hover:bg-accent-hover text-accent-on text-xs font-bold transition-all shadow-md cursor-pointer"
                >
                  <span>{activeFeature.actionLabel}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
