import { DatabaseSchema, SchemaTable, SchemaColumn, SchemaRelation } from '../types/schema';

const TYPE_MAP: Record<string, string> = {
  INT: 'Int', BIGINT: 'BigInt', SMALLINT: 'Int', TINYINT: 'Int',
  FLOAT: 'Float', DECIMAL: 'Decimal', NUMERIC: 'Decimal',
  BOOLEAN: 'Boolean', BOOL: 'Boolean',
  VARCHAR: 'String', NVARCHAR: 'String', CHAR: 'String', TEXT: 'String', NTEXT: 'String',
  DATE: 'DateTime', DATETIME: 'DateTime', TIMESTAMP: 'DateTime', TIME: 'DateTime',
  JSON: 'Json', JSONB: 'Json',
  UUID: 'String', UNIQUEIDENTIFIER: 'String',
  BLOB: 'Bytes', BINARY: 'Bytes', VARBINARY: 'Bytes',
};

function toPrismaType(sqlType: string): string {
  const base = sqlType.toUpperCase().replace(/\s*\(.*\)/, '');
  return TYPE_MAP[base] ?? 'String';
}

function toCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function toPascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

export function toPrismaSchema(schema: DatabaseSchema): string {
  const lines: string[] = [];

  // Datasource + generator header
  lines.push('// Generated by Namines Schema Designer');
  lines.push('// Replace the datasource provider with your actual database.');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql"');
  lines.push('  url      = env("DATABASE_URL")');
  lines.push('}');
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');

  // Build lookup maps
  const tableById = new Map<string, SchemaTable>(schema.tables.map(t => [t.id, t]));
  const colById = new Map<string, SchemaColumn>();
  for (const t of schema.tables) {
    for (const c of t.columns) colById.set(c.id, c);
  }

  // Relations grouped by source table
  const relsBySource = new Map<string, SchemaRelation[]>();
  const relsByTarget = new Map<string, SchemaRelation[]>();
  for (const r of schema.relations) {
    if (!relsBySource.has(r.sourceTableId)) relsBySource.set(r.sourceTableId, []);
    if (!relsByTarget.has(r.targetTableId)) relsByTarget.set(r.targetTableId, []);
    relsBySource.get(r.sourceTableId)!.push(r);
    relsByTarget.get(r.targetTableId)!.push(r);
  }

  for (const table of schema.tables) {
    lines.push(`model ${toPascalCase(table.name)} {`);

    for (const col of table.columns) {
      const prismaType = toPrismaType(col.type);
      const nullable = col.isNullable && !col.isPK ? '?' : '';
      const attrs: string[] = [];
      if (col.isPK) {
        attrs.push('@id');
        if (prismaType === 'Int') attrs.push('@default(autoincrement())');
        if (prismaType === 'String') attrs.push('@default(uuid())');
      }
      if (col.defaultValue) {
        const def = col.defaultValue.trim();
        if (prismaType === 'String') attrs.push(`@default("${def}")`);
        else attrs.push(`@default(${def})`);
      }
      const attrsStr = attrs.length ? '  ' + attrs.join(' ') : '';
      lines.push(`  ${col.name.padEnd(24)} ${prismaType}${nullable}${attrsStr}`);
    }

    // FK relation fields (source side → @relation)
    const sourceRels = relsBySource.get(table.id) ?? [];
    for (const r of sourceRels) {
      const targetTable = tableById.get(r.targetTableId);
      if (!targetTable) continue;
      const sourceCol = colById.get(r.sourceColumnId);
      const targetCol = colById.get(r.targetColumnId);
      if (!sourceCol || !targetCol) continue;
      const fieldName = toCamelCase(targetTable.name);
      lines.push(`  ${fieldName.padEnd(24)} ${toPascalCase(targetTable.name)}  @relation(fields: [${sourceCol.name}], references: [${targetCol.name}])`);
    }

    // Back-relation fields (target side)
    const targetRels = relsByTarget.get(table.id) ?? [];
    for (const r of targetRels) {
      const sourceTable = tableById.get(r.sourceTableId);
      if (!sourceTable) continue;
      const fieldName = toCamelCase(sourceTable.name) + 's';
      lines.push(`  ${fieldName.padEnd(24)} ${toPascalCase(sourceTable.name)}[]`);
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}
