using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging.Abstractions;
using Namines.Core.Enums;
using Namines.Infrastructure.Services;
using Oracle.ManagedDataAccess.Client;
using Testcontainers.Oracle;
using Xunit;

namespace Namines.Tests.Integration;

/// <summary>
/// <see cref="DbIntrospectionService"/>'in Oracle katalog sorgularını GERÇEK bir
/// Oracle'a karşı doğrular (backlog B-12'nin Oracle yarısı).
///
/// <b>Neden yazıldı:</b> Oracle yolu yazıldığından beri hiç gerçek bir sunucuya
/// karşı koşmadı — makinede imaj yoktu ve diskte yer yoktu, kodun kendisi
/// "⚠️ CANLI DOĞRULANMADI" diyordu.
///
/// <b>Neden <see cref="EngineAvailable"/> değil <see cref="RequiresDockerFactAttribute"/>:</b>
/// Oracle'ın bir <c>ContainerProfile</c>'ı yok, çünkü Docker sandbox'ı Oracle
/// desteklemiyor. Yalnızca bu test için profil eklemek, sandbox'ın Oracle
/// açabildiği izlenimini verirdi.
/// </summary>
[Collection("Docker")]
public class OracleIntrospectionTests : IAsyncLifetime
{
    private readonly OracleContainer _container =
        new OracleBuilder("gvenzl/oracle-free:23-slim-faststart").Build();

    public Task InitializeAsync() =>
        DockerAvailable.Value ? _container.StartAsync() : Task.CompletedTask;

    public Task DisposeAsync() =>
        DockerAvailable.Value ? _container.DisposeAsync().AsTask() : Task.CompletedTask;

    // Oracle'da ifade sonundaki ';' sözdizimi hatası — her ifade ayrı gönderiliyor.
    private static readonly string[] Schema =
    [
        """
        CREATE TABLE musteri (
            id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            eposta VARCHAR2(200) NOT NULL CONSTRAINT uq_musteri_eposta UNIQUE,
            ad     VARCHAR2(100) NOT NULL,
            bakiye NUMBER(12,2) DEFAULT 0 NOT NULL,
            sayac  NUMBER(12) NULL,
            CONSTRAINT ck_bakiye CHECK (bakiye >= 0)
        )
        """,
        """
        CREATE TABLE siparis (
            id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            musteri_id NUMBER NOT NULL,
            tutar      NUMBER(10,2) NOT NULL,
            CONSTRAINT fk_siparis_musteri FOREIGN KEY (musteri_id)
                REFERENCES musteri(id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX ix_siparis_musteri ON siparis (musteri_id)",
    ];

    private async Task<Core.Models.DatabaseSchema> IntrospectAsync()
    {
        var connectionString = _container.GetConnectionString();

        await using (var connection = new OracleConnection(connectionString))
        {
            await connection.OpenAsync();
            foreach (var statement in Schema)
            {
                await using var command = new OracleCommand(statement, connection);
                await command.ExecuteNonQueryAsync();
            }
        }

        var service = new DbIntrospectionService(
            NullLogger<DbIntrospectionService>.Instance, new AlwaysAllowHostPolicy());
        return await service.IntrospectAsync(connectionString, "Oracle", CancellationToken.None);
    }

    // Oracle tırnaksız adları BÜYÜK harfe çevirir; eşleştirme harf duyarsız.
    private static Core.Models.SchemaTable Table(Core.Models.DatabaseSchema schema, string name) =>
        schema.Tables.Single(t => string.Equals(t.Name, name, StringComparison.OrdinalIgnoreCase));

    private static Core.Models.SchemaColumn Column(Core.Models.SchemaTable table, string name) =>
        table.Columns.Single(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase));

    [RequiresDockerFact]
    public async Task Reads_tables_columns_and_numeric_precision()
    {
        var schema = await IntrospectAsync();

        Assert.Equal(2, schema.Tables.Count);
        var musteri = Table(schema, "musteri");

        var id = Column(musteri, "id");
        Assert.True(id.IsPK);

        var eposta = Column(musteri, "eposta");
        Assert.Equal(200, eposta.Length);
        Assert.False(eposta.IsNullable);

        // NUMBER(12,2): uzunluk DATA_PRECISION'dan, ölçek DATA_SCALE'den gelmeli.
        // Oracle sayısal kolonlarda CHAR_LENGTH'i 0 döndürür; 0 bir "bilinen
        // uzunluk" sanılırsa DDL yeniden üretilirken NUMBER(0,2) yazılırdı.
        var bakiye = Column(musteri, "bakiye");
        // Oracle'ın tek sayı tipi NUMBER: ölçeği olan kolon DECIMAL okunmalı.
        // INT okunursa şema yeniden üretildiğinde küsurat (kuruş) sessizce kaybolur.
        Assert.Equal("DECIMAL", bakiye.Type);
        Assert.Equal(12, bakiye.Length);
        Assert.Equal(2, bakiye.Scale);
        Assert.False(bakiye.IsNullable);

        // 12 haneli tamsayı INT'e (en çok 10 hane) sığmaz.
        Assert.Equal("BIGINT", Column(musteri, "sayac").Type);
    }

    [RequiresDockerFact]
    public async Task Identity_is_reported_as_unknown_not_as_false()
    {
        var schema = await IntrospectAsync();
        var id = Column(Table(schema, "musteri"), "id");

        // Oracle yolu varsayılan/identity bilgisini BİLEREK okumuyor (DATA_DEFAULT
        // bir LONG kolonu). Doğru cevap null = "söylenmedi"; false yazmak
        // "kesinlikle otomatik değil" iddiası olurdu.
        Assert.Null(id.Identity);
    }

    [RequiresDockerFact]
    public async Task Reads_unique_constraints_and_indexes()
    {
        var schema = await IntrospectAsync();
        var musteri = Table(schema, "musteri");
        var siparis = Table(schema, "siparis");
        var eposta = Column(musteri, "eposta");

        Assert.Contains(musteri.Uniques, u => u.ColumnIds.Contains(eposta.Id));
        Assert.Contains(siparis.Indexes,
            i => string.Equals(i.Name, "ix_siparis_musteri", StringComparison.OrdinalIgnoreCase));
    }

    [RequiresDockerFact]
    public async Task Reads_foreign_keys_with_referential_action()
    {
        var schema = await IntrospectAsync();
        var siparis = Table(schema, "siparis");
        var musteri = Table(schema, "musteri");

        var fk = Column(siparis, "musteri_id");
        Assert.True(fk.IsFK);

        var relation = Assert.Single(schema.Relations, r =>
            r.SourceTableId == siparis.Id && r.SourceColumnId == fk.Id && r.TargetTableId == musteri.Id);
        Assert.Equal(ReferentialAction.Cascade, relation.OnDelete);
        // Oracle'da ON UPDATE yok; sorgu bunu kesin olarak NO ACTION bildiriyor.
        Assert.Equal(ReferentialAction.NoAction, relation.OnUpdate);
    }

    /// <summary>
    /// Testte SSRF politikası devre dışı: konteynerin adresi özel bir adres ve
    /// üretim politikası onu haklı olarak reddediyor. Test edilen şey katalog
    /// SQL'i, politikanın kendisi değil (o ayrıca test ediliyor).
    /// </summary>
    private sealed class AlwaysAllowHostPolicy : Core.Security.IDbHostAccessPolicy
    {
        public bool IsHostAllowed(string? host, out string denyReason)
        {
            denyReason = string.Empty;
            return true;
        }
    }
}
